/*
 * SYSTICK_Delay.h
 *
 *  Created on: 18 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_APP_SYSTICK_DELAY_H_
#define XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_APP_SYSTICK_DELAY_H_

void SysTick__vDelayUs(float fTimeUs);

#endif /* XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_APP_SYSTICK_DELAY_H_ */
