/**
 *
 * @file DMA_RegisterPeripheralChannel_Bitbanding.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 29 jul. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 29 jul. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERALCHANNEL_BITBANDING_H_
#define XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERALCHANNEL_BITBANDING_H_

#include <xDriver_MCU/DMA/Peripheral/Register/xHeader/DMA_RegisterAddressChannel.h>
#include <xDriver_MCU/DMA/Peripheral/Register/RegisterDefines/DMA_RegisterDefines.h>
#include <xDriver_MCU/DMA/Peripheral/Struct/xHeader/DMA_StructPeripheralChannel_Bitbanding.h>

#define DMACH_BITBANDING    ((DMACH_BITBANDING_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + (DMACH_OFFSET * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING    ((DMACH_BITBANDING_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + (DMAALTCH_OFFSET * (uint32_t) 32UL)))

/********************************************************************************************
************************************** 1 SRCENDP **********************************************
********************************************************************************************/
#define DMACH_BITBANDING_SRCENDP0    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH0_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP1    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH1_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP2    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH2_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP3    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH3_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP4    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH4_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP5    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH5_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP6    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH6_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP7    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH7_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP8    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH8_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP9    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH9_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP10    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH10_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP11    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH11_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP12    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH12_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP13    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH13_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP14    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH14_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP15    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH15_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP16    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH16_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP17    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH17_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP18    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH18_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP19    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH19_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP20    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH20_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP21    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH21_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP22    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH22_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP23    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH23_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP24    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH24_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP25    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH25_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP26    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH26_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP27    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH27_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP28    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH28_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP29    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH29_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP30    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH30_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_SRCENDP31    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH31_OFFSET + DMACH_SRCENDP_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** ALT 1 SRCENDP **********************************************
********************************************************************************************/
#define DMAALTCH_BITBANDING_SRCENDP0    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH0_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP1    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH1_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP2    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH2_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP3    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH3_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP4    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH4_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP5    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH5_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP6    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH6_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP7    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH7_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP8    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH8_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP9    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH9_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP10    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH10_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP11    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH11_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP12    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH12_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP13    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH13_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP14    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH14_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP15    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH15_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP16    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH16_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP17    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH17_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP18    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH18_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP19    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH19_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP20    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH20_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP21    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH21_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP22    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH22_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP23    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH23_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP24    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH24_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP25    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH25_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP26    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH26_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP27    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH27_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP28    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH28_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP29    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH29_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP30    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH30_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_SRCENDP31    ((BITBANDING_DMASRCENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH31_OFFSET + DMAALTCH_SRCENDP_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** 2 DSTENDP **********************************************
********************************************************************************************/
#define DMACH_BITBANDING_DSTENDP0    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH0_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP1    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH1_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP2    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH2_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP3    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH3_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP4    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH4_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP5    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH5_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP6    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH6_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP7    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH7_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP8    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH8_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP9    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH9_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP10    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH10_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP11    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH11_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP12    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH12_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP13    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH13_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP14    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH14_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP15    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH15_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP16    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH16_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP17    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH17_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP18    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH18_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP19    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH19_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP20    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH20_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP21    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH21_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP22    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH22_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP23    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH23_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP24    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH24_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP25    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH25_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP26    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH26_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP27    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH27_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP28    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH28_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP29    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH29_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP30    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH30_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_DSTENDP31    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH31_OFFSET + DMACH_DSTENDP_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** ALT 2 DSTENDP **********************************************
********************************************************************************************/
#define DMAALTCH_BITBANDING_DSTENDP0    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH0_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP1    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH1_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP2    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH2_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP3    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH3_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP4    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH4_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP5    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH5_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP6    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH6_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP7    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH7_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP8    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH8_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP9    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH9_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP10    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH10_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP11    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH11_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP12    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH12_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP13    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH13_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP14    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH14_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP15    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH15_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP16    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH16_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP17    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH17_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP18    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH18_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP19    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH19_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP20    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH20_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP21    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH21_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP22    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH22_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP23    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH23_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP24    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH24_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP25    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH25_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP26    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH26_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP27    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH27_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP28    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH28_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP29    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH29_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP30    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH30_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_DSTENDP31    ((BITBANDING_DMADSTENDP_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH31_OFFSET + DMAALTCH_DSTENDP_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** 3 CHCTL **********************************************
********************************************************************************************/
#define DMACH_BITBANDING_CHCTL0    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH0_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL1    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH1_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL2    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH2_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL3    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH3_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL4    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH4_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL5    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH5_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL6    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH6_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL7    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH7_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL8    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH8_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL9    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH9_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL10    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH10_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL11    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH11_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL12    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH12_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL13    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH13_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL14    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH14_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL15    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH15_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL16    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH16_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL17    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH17_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL18    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH18_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL19    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH19_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL20    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH20_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL21    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH21_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL22    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH22_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL23    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH23_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL24    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH24_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL25    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH25_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL26    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH26_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL27    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH27_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL28    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH28_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL29    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH29_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL30    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH30_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMACH_BITBANDING_CHCTL31    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMACH_BITBANDING_BASE + ((DMACH31_OFFSET + DMACH_CHCTL_OFFSET) * (uint32_t) 32UL)))

/********************************************************************************************
************************************** ALT 3 CHCTL **********************************************
********************************************************************************************/
#define DMAALTCH_BITBANDING_CHCTL0    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH0_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL1    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH1_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL2    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH2_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL3    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH3_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL4    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH4_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL5    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH5_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL6    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH6_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL7    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH7_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL8    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH8_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL9    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH9_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL10    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH10_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL11    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH11_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL12    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH12_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL13    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH13_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL14    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH14_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL15    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH15_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL16    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH16_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL17    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH17_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL18    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH18_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL19    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH19_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL20    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH20_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL21    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH21_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL22    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH22_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL23    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH23_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL24    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH24_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL25    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH25_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL26    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH26_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL27    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH27_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL28    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH28_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL29    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH29_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL30    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH30_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))
#define DMAALTCH_BITBANDING_CHCTL31    ((BITBANDING_DMACHCTL_TypeDef*) ((uint32_t) DMAALTCH_BITBANDING_BASE + ((DMAALTCH31_OFFSET + DMAALTCH_CHCTL_OFFSET) * (uint32_t) 32UL)))


#endif /* XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERALCHANNEL_BITBANDING_H_ */
