/**
 *
 * @file DCMotorController_Defines.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ene. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ene. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XCARMODULES_DCMOTORCONTROLLER_XHEADER_DCMOTORCONTROLLER_DEFINES_H_
#define XCARMODULES_DCMOTORCONTROLLER_XHEADER_DCMOTORCONTROLLER_DEFINES_H_

#include <xUtils/Standard/Standard.h>
#include <xDriver_MCU/xDriver_MCU.h>


/*Tail to Head*/

/*MOTOR RIGHT IO A10*/
#define MOTOR_PERIOD_TICKS (100UL)
#define MOTOR_RIGHT_ENABLE_FUNCTION (GPIO_enM1PWM2)
#define MOTOR_RIGHT_ENABLE_PORT (GPIO_enPORT_A)
#define MOTOR_RIGHT_ENABLE_PIN (GPIO_enPIN_6)
#define MOTOR_RIGHT_ENABLE_MODULE (PWM_enMODULE_1)
#define MOTOR_RIGHT_ENABLE_OUTPUT (PWM_enOUTPUT_A)
#define MOTOR_RIGHT_ENABLE_GENERATOR (PWM_enGEN_1)
#define MOTOR_RIGHT_ENABLE_GENMASK (PWM_enGENMASK_1)

/*FORWARD*/
#define MOTOR_RIGHT_FORWARD_FUNCTION (GPIO_enGPIOE0)
#define MOTOR_RIGHT_FORWARD_PORT (GPIO_enPORT_E)
#define MOTOR_RIGHT_FORWARD_PIN (GPIO_enPIN_0)

/*BACKWARD*/
#define MOTOR_RIGHT_BACKWARD_FUNCTION (GPIO_enGPIOE3)
#define MOTOR_RIGHT_BACKWARD_PORT (GPIO_enPORT_E)
#define MOTOR_RIGHT_BACKWARD_PIN (GPIO_enPIN_3)

#define MOTOR_RIGHT_PHASEA_FUNCTION (GPIO_enPhA0)
#define MOTOR_RIGHT_PHASEA_PORT (GPIO_enPORT_D)
#define MOTOR_RIGHT_PHASEA_PIN (GPIO_enPIN_6)

#define MOTOR_RIGHT_PHASEB_FUNCTION (GPIO_enPhB0)
#define MOTOR_RIGHT_PHASEB_PORT (GPIO_enPORT_D)
#define MOTOR_RIGHT_PHASEB_PIN (GPIO_enPIN_7)

/*MOTOR LEFT IO A11*/
#define MOTOR_LEFT_ENABLE_FUNCTION (GPIO_enM1PWM3)
#define MOTOR_LEFT_ENABLE_PORT (GPIO_enPORT_A)
#define MOTOR_LEFT_ENABLE_PIN (GPIO_enPIN_7)
#define MOTOR_LEFT_ENABLE_MODULE (PWM_enMODULE_1)
#define MOTOR_LEFT_ENABLE_OUTPUT (PWM_enOUTPUT_B)
#define MOTOR_LEFT_ENABLE_GENERATOR (PWM_enGEN_1)
#define MOTOR_LEFT_ENABLE_GENMASK (PWM_enGENMASK_1)

/*FORWARD*/
#define MOTOR_LEFT_FORWARD_FUNCTION (GPIO_enGPIOC4)
#define MOTOR_LEFT_FORWARD_PORT (GPIO_enPORT_C)
#define MOTOR_LEFT_FORWARD_PIN (GPIO_enPIN_4)

/*BACKWARD*/
#define MOTOR_LEFT_BACKWARD_FUNCTION (GPIO_enGPIOC7)
#define MOTOR_LEFT_BACKWARD_PORT (GPIO_enPORT_C)
#define MOTOR_LEFT_BACKWARD_PIN (GPIO_enPIN_7)

#define MOTOR_LEFT_PHASEA_FUNCTION (GPIO_enPhA1)
#define MOTOR_LEFT_PHASEA_PORT (GPIO_enPORT_C)
#define MOTOR_LEFT_PHASEA_PIN (GPIO_enPIN_5)

#define MOTOR_LEFT_PHASEB_FUNCTION (GPIO_enPhB1)
#define MOTOR_LEFT_PHASEB_PORT (GPIO_enPORT_C)
#define MOTOR_LEFT_PHASEB_PIN (GPIO_enPIN_6)


typedef enum
{
    DCMOTOR_enDIRECTION_FORWARD = 0UL,
    DCMOTOR_enDIRECTION_BACKWARD = 1UL,
    DCMOTOR_enDIRECTION_STOP = 2UL,
}DCMOTOR_nDIRECTION;

typedef enum
{
    DCMOTOR_enMOTOR_LEFT = 0UL,
    DCMOTOR_enMOTOR_RIGHT = 1UL,
    DCMOTOR_enMOTOR_BOTH = 2UL,
}DCMOTOR_nMOTOR;

typedef enum
{
    DCMOTOR_enENABLE_DIS = 0UL,
    DCMOTOR_enENABLE_ENA = 1UL,
}DCMOTOR_nENABLE;

#endif /* XCARMODULES_DCMOTORCONTROLLER_XHEADER_DCMOTORCONTROLLER_DEFINES_H_ */
