/*
 * COMP.c
 *
 *  Created on: 27 abr. 2018
 *      Author: InDev
 */


#include <COMP.h>


int COMP_Init(void)
{
    long delay=0;

    SYSCTL_RCGCACMP_RCGCACMP_BB=1;
    SYSCTL_RCGCGPIO_RCGCGPIOC_BB=1;
    delay =SYSCTL_RCGCGPIO_RCGCGPIOC_BB;
    SYSCTL_RCGCGPIO_RCGCGPIOF_BB=1;
    delay =SYSCTL_RCGCGPIO_RCGCGPIOF_BB;


    GPIOC_AHB->GPIOLOCK=GPIOC_AHB_GPIOLOCK_LOCK_KEY;
    GPIOC_AHB->GPIOCR|=(PIN4|PIN5|PIN6|PIN7);
    GPIOC_AHB->GPIOAFSEL |= (PIN4|PIN5|PIN6|PIN7);
    GPIOC_AHB->GPIOAMSEL |= (PIN4|PIN5|PIN6|PIN7);
    GPIOC_AHB->GPIODEN &=~ (PIN4|PIN5|PIN6|PIN7);


    GPIOF_AHB->GPIOLOCK=GPIOF_AHB_GPIOLOCK_LOCK_KEY;
    GPIOF_AHB->GPIOCR|=(PIN0|PIN1);
    GPIOF_AHB->GPIOAFSEL |= (PIN0|PIN1);

    GPIOF_AHB->GPIOAMSEL &=~ (PIN0|PIN1);
    GPIOF_AHB_GPIOPCTL->PMC0=9;
    GPIOF_AHB_GPIOPCTL->PMC1=9;
    GPIOF_AHB->GPIODEN |= (PIN0|PIN1);

    COMP_ACREFCTL_RNG_BB=1;
    COMP_ACREFCTL->VREF=0xC;
    COMP_ACREFCTL_EN_BB=1;

    COMP_ACCTL0_CINV_BB=0;
    COMP_ACCTL0->ISEN=3;
    COMP_ACCTL0->ASRCP=2;
    for(delay=0; delay<1000000; delay++);


    COMP_ACCTL1_CINV_BB=0;
    COMP_ACCTL1->ISEN=3;
    COMP_ACCTL1->ASRCP=0;
    for(delay=0; delay<10000000; delay++);


    COMP_ACINTEN_IN0_BB=1;
    COMP_ACINTEN_IN1_BB=1;

    NVIC_EN0->NVIC_COMP0=1;
    NVIC_EN0->NVIC_COMP1=1;

    NVIC_PRI6->NVIC_COMP0 =7;
    NVIC_PRI6->NVIC_COMP1 =7;

    return 1;
}




void COMP0_Handler(void)
{
    if(COMP_ACMIS_IN0_BB)
    {
        COMP_ACMIS_IN0_BB=1;
    }
}
void COMP1_Handler(void)
{
    if(COMP_ACMIS_IN1_BB)
    {
        COMP_ACMIS_IN1_BB=1;
    }

}
