/*
 * FPU_Enum.h
 *
 *  Created on: 17 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_


typedef enum
{
    FPU_enOK =0U,
    FPU_enERROR =1U,
}FPU_nSTATUS;

typedef enum
{
    FPU_enDENIED =0U,
    FPU_enONLY_PRIVILEGED =1U,
    FPU_enFULL_ACCESS =3U,
}FPU_nACCESS;

typedef enum
{
    FPU_enLAZY_PRESERVATION_DIS =0U,
    FPU_enLAZY_PRESERVATION_EN =1U,
}FPU_nLAZY_PRESERVATION;

typedef enum
{
    FPU_enAUTO_PRESERVATION_DIS =0U,
    FPU_enAUTO_PRESERVATION_EN =1U,
}FPU_nAUTO_PRESERVATION;

typedef enum
{
    FPU_enPRESERVATION_NOACTIVE =0U,
    FPU_enPRESERVATION_ACTIVE =1U,
}FPU_nPRESERVATION_STATUS;

typedef enum
{
    FPU_enHALF_PRECISION_IEEE =0U,
    FPU_enHALF_PRECISION_ALT =1U,
}FPU_nHALF_PRECISION;

typedef enum
{
    FPU_enNAN_PROPAGATE =0U,
    FPU_enNAN_NAN =1U,
}FPU_nNAN;

typedef enum
{
    FPU_enROUNDING_NEAREST =0U,
    FPU_enROUNDING_PLUSINF =1U,
    FPU_enROUNDING_MINUSINF =2U,
    FPU_enROUNDING_ZERO =3U,
}FPU_nROUNDING;

typedef enum
{
    FPU_enEXCEPTION_DENORMAL=0x80U,
    FPU_enEXCEPTION_INEXACT=0x10U,
    FPU_enEXCEPTION_UNDERFLOW=0x08U,
    FPU_enEXCEPTION_OVERFLOW=0x04U,
    FPU_enEXCEPTION_DIV0=0x02U,
    FPU_enEXCEPTION_INVALID=0x01U,
}FPU_nEXCEPTION;



#endif /* XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_ */
