/**
 *
 * @file DMA_RegisterPeripheral_Bitbanding.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 28 jul. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 28 jul. 2020     vyldram    1.0         initial Version@endverbatim
 */
#ifndef XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_
#define XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_

#include <xDriver_MCU/Driver_Header/DMA/DMA_Peripheral/DMA_Struct/DMA_StructPeripheral_Bitbanding.h>
#include <xDriver_MCU/Driver_Header/DMA/DMA_Peripheral/DMA_Register/DMA_RegisterAddress.h>
#include <xDriver_MCU/Driver_Header/DMA/DMA_Peripheral/DMA_Register/DMA_RegisterDefines/DMA_RegisterDefines.h>

#define DMA_BITBANDING        (((DMA_BITBANDING_TypeDef*)(DMA_BITBANDING_BASE+(DMA_OFFSET*32u))))

/********************************************************************************************
************************************** 4 DMASTAT **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMASTAT       (((BITBANDING_DMASTAT_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASTAT_OFFSET)*32u))))

#define DMA_BITBANDING_DMASTAT_MASTEN         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASTAT_OFFSET)*32u)+(DMA_DMASTAT_R_MASTEN_BIT*4u))))

/********************************************************************************************
************************************** 5 DMACFG **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMACFG       (((BITBANDING_DMACFG_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACFG_OFFSET)*32u))))

#define DMA_BITBANDING_DMACFG_MASTEN         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACFG_OFFSET)*32u)+(DMA_DMACFG_R_MASTEN_BIT*4u))))

/********************************************************************************************
************************************** 6 DMACTLBASE **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMACTLBASE       (((BITBANDING_DMACTLBASE_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACTLBASE_OFFSET)*32u))))

/********************************************************************************************
************************************** 7 DMAALTBASE **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAALTBASE       (((BITBANDING_DMAALTBASE_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTBASE_OFFSET)*32u))))

/********************************************************************************************
************************************** 8 DMAWAITSTAT **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAWAITSTAT       (((BITBANDING_DMAWAITSTAT_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u))))

#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ0         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ0_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ1         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ1_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ2         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ2_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ3         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ3_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ4         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ4_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ5         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ5_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ6         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ6_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ7         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ7_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ8         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ8_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ9         (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ9_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ10        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ10_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ11        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ11_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ12        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ12_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ13        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ13_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ14        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ14_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ15        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ15_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ16        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ16_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ17        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ17_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ18        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ18_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ19        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ19_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ20        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ20_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ21        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ21_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ22        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ22_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ23        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ23_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ24        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ24_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ25        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ25_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ26        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ26_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ27        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ27_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ28        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ28_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ29        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ29_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ30        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ30_BIT*4u))))
#define DMA_BITBANDING_DMAWAITSTAT_WAITREQ31        (*((volatile const uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAWAITSTAT_OFFSET)*32u)+(DMA_DMAWAITSTAT_R_WAITREQ31_BIT*4u))))

/********************************************************************************************
************************************** 9 DMASWREQ **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMASWREQ       (((BITBANDING_DMASWREQ_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u))))

#define DMA_BITBANDING_DMASWREQ_SWREQ0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ0_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ1_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ2_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ3_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ4_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ5_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ6_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ7_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ8_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ9_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ10_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ11_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ12_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ13_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ14_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ15_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ16_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ17_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ18_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ19_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ20_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ21_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ22_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ23_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ24_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ25_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ26_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ27_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ28_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ29_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ30_BIT*4u))))
#define DMA_BITBANDING_DMASWREQ_SWREQ31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMASWREQ_OFFSET)*32u)+(DMA_DMASWREQ_R_SWREQ31_BIT*4u))))

/********************************************************************************************
************************************** 10 DMAUSEBURSTSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAUSEBURSTSET       (((BITBANDING_DMASET_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u))))

#define DMA_BITBANDING_DMAUSEBURSTSET_SET0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET0_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET1_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET2_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET3_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET4_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET5_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET6_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET7_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET8_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET9_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET10_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET11_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET12_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET13_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET14_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET15_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET16_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET17_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET18_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET19_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET20_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET21_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET22_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET23_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET24_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET25_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET26_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET27_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET28_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET29_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET30_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTSET_SET31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTSET_OFFSET)*32u)+(DMA_DMAUSEBURSTSET_R_SET31_BIT*4u))))

/********************************************************************************************
************************************** 11 DMAUSEBURSTCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAUSEBURSTCLR       (((BITBANDING_DMACLR_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u))))

#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR0_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR1_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR2_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR3_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR4_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR5_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR6_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR7_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR8_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR9_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR10_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR11_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR12_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR13_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR14_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR15_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR16_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR17_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR18_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR19_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR20_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR21_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR22_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR23_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR24_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR25_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR26_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR27_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR28_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR29_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR30_BIT*4u))))
#define DMA_BITBANDING_DMAUSEBURSTCLR_CLR31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAUSEBURSTCLR_OFFSET)*32u)+(DMA_DMAUSEBURSTCLR_R_CLR31_BIT*4u))))

/********************************************************************************************
************************************** 12 DMAREQMASKSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAREQMASKSET       (((BITBANDING_DMASET_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u))))

#define DMA_BITBANDING_DMAREQMASKSET_SET0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET0_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET1_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET2_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET3_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET4_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET5_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET6_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET7_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET8_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET9_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET10_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET11_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET12_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET13_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET14_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET15_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET16_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET17_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET18_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET19_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET20_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET21_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET22_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET23_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET24_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET25_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET26_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET27_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET28_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET29_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET30_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKSET_SET31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKSET_OFFSET)*32u)+(DMA_DMAREQMASKSET_R_SET31_BIT*4u))))

/********************************************************************************************
************************************** 13 DMAREQMASKCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAREQMASKCLR       (((BITBANDING_DMACLR_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u))))

#define DMA_BITBANDING_DMAREQMASKCLR_CLR0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR0_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR1_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR2_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR3_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR4_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR5_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR6_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR7_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR8_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR9_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR10_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR11_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR12_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR13_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR14_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR15_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR16_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR17_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR18_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR19_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR20_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR21_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR22_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR23_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR24_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR25_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR26_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR27_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR28_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR29_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR30_BIT*4u))))
#define DMA_BITBANDING_DMAREQMASKCLR_CLR31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAREQMASKCLR_OFFSET)*32u)+(DMA_DMAREQMASKCLR_R_CLR31_BIT*4u))))


/********************************************************************************************
************************************** 14 DMAENASET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAENASET       (((BITBANDING_DMASET_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u))))

#define DMA_BITBANDING_DMAENASET_SET0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET0_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET1_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET2_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET3_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET4_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET5_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET6_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET7_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET8_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET9_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET10_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET11_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET12_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET13_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET14_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET15_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET16_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET17_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET18_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET19_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET20_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET21_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET22_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET23_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET24_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET25_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET26_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET27_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET28_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET29_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET30_BIT*4u))))
#define DMA_BITBANDING_DMAENASET_SET31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENASET_OFFSET)*32u)+(DMA_DMAENASET_R_SET31_BIT*4u))))

/********************************************************************************************
************************************** 15 DMAENACLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAENACLR       (((BITBANDING_DMACLR_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u))))

#define DMA_BITBANDING_DMAENACLR_CLR0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR0_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR1_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR2_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR3_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR4_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR5_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR6_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR7_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR8_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR9_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR10_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR11_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR12_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR13_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR14_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR15_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR16_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR17_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR18_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR19_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR20_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR21_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR22_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR23_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR24_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR25_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR26_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR27_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR28_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR29_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR30_BIT*4u))))
#define DMA_BITBANDING_DMAENACLR_CLR31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAENACLR_OFFSET)*32u)+(DMA_DMAENACLR_R_CLR31_BIT*4u))))

/********************************************************************************************
************************************** 16 DMAALTSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAALTSET       (((BITBANDING_DMASET_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u))))

#define DMA_BITBANDING_DMAALTSET_SET0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET0_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET1_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET2_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET3_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET4_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET5_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET6_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET7_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET8_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET9_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET10_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET11_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET12_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET13_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET14_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET15_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET16_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET17_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET18_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET19_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET20_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET21_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET22_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET23_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET24_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET25_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET26_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET27_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET28_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET29_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET30_BIT*4u))))
#define DMA_BITBANDING_DMAALTSET_SET31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTSET_OFFSET)*32u)+(DMA_DMAALTSET_R_SET31_BIT*4u))))

/********************************************************************************************
************************************** 17 DMAALTCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAALTCLR       (((BITBANDING_DMACLR_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u))))

#define DMA_BITBANDING_DMAALTCLR_CLR0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR0_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR1_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR2_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR3_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR4_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR5_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR6_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR7_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR8_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR9_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR10_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR11_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR12_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR13_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR14_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR15_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR16_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR17_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR18_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR19_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR20_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR21_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR22_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR23_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR24_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR25_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR26_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR27_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR28_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR29_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR30_BIT*4u))))
#define DMA_BITBANDING_DMAALTCLR_CLR31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAALTCLR_OFFSET)*32u)+(DMA_DMAALTCLR_R_CLR31_BIT*4u))))

/********************************************************************************************
************************************* 18 DMAPRIOSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPRIOSET       (((BITBANDING_DMASET_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u))))

#define DMA_BITBANDING_DMAPRIOSET_SET0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET0_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET1_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET2_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET3_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET4_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET5_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET6_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET7_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET8_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET9_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET10_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET11_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET12_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET13_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET14_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET15_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET16_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET17_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET18_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET19_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET20_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET21_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET22_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET23_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET24_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET25_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET26_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET27_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET28_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET29_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET30_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOSET_SET31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOSET_OFFSET)*32u)+(DMA_DMAPRIOSET_R_SET31_BIT*4u))))

/********************************************************************************************
************************************** 19 DMAPRIOCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPRIOCLR       (((BITBANDING_DMACLR_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u))))

#define DMA_BITBANDING_DMAPRIOCLR_CLR0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR0_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR1_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR2_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR3_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR4_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR5_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR6_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR7_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR8_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR9_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR10_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR11_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR12_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR13_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR14_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR15_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR16_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR17_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR18_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR19_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR20_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR21_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR22_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR23_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR24_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR25_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR26_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR27_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR28_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR29_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR30_BIT*4u))))
#define DMA_BITBANDING_DMAPRIOCLR_CLR31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPRIOCLR_OFFSET)*32u)+(DMA_DMAPRIOCLR_R_CLR31_BIT*4u))))

/********************************************************************************************
************************************** 20 DMAERRCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAERRCLR       (((BITBANDING_DMAERRCLR_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAERRCLR_OFFSET)*32u))))

#define DMA_BITBANDING_DMAERRCLR_ERRCLR         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAERRCLR_OFFSET)*32u)+(DMA_DMAERRCLR_R_ERRCLR_BIT*4u))))

/********************************************************************************************
************************************** 21 DMACHASGN **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMACHASGN       (((BITBANDING_DMACHASGN_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u))))

#define DMA_BITBANDING_DMACHASGN_CHASGN0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN0_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN1_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN2_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN3_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN4_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN5_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN6_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN7_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN8_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN9_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN10_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN11_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN12_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN13_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN14_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN15_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN16_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN17_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN18_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN19_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN20_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN21_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN22_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN23_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN24_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN25_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN26_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN27_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN28_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN29_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN30_BIT*4u))))
#define DMA_BITBANDING_DMACHASGN_CHASGN31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHASGN_OFFSET)*32u)+(DMA_DMACHASGN_R_CHASGN31_BIT*4u))))

/********************************************************************************************
************************************** 22 DMACHIS **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMACHIS       (((BITBANDING_DMACHIS_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u))))

#define DMA_BITBANDING_DMACHIS_CHIS0         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS0_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS1         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS1_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS2         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS2_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS3         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS3_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS4         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS4_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS5         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS5_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS6         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS6_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS7         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS7_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS8         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS8_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS9         (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS9_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS10        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS10_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS11        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS11_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS12        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS12_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS13        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS13_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS14        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS14_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS15        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS15_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS16        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS16_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS17        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS17_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS18        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS18_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS19        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS19_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS20        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS20_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS21        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS21_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS22        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS22_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS23        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS23_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS24        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS24_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS25        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS25_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS26        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS26_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS27        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS27_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS28        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS28_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS29        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS29_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS30        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS30_BIT*4u))))
#define DMA_BITBANDING_DMACHIS_CHIS31        (*((volatile uint32_t *)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHIS_OFFSET)*32u)+(DMA_DMACHIS_R_CHIS31_BIT*4u))))

/********************************************************************************************
************************************** 23 DMACHMAP0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMACHMAP0       (((BITBANDING_DMACHMAP0_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHMAP0_OFFSET)*32u))))

/********************************************************************************************
************************************** 24 DMACHMAP1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMACHMAP1       (((BITBANDING_DMACHMAP1_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHMAP1_OFFSET)*32u))))

/********************************************************************************************
************************************** 25 DMACHMAP2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMACHMAP2       (((BITBANDING_DMACHMAP2_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHMAP2_OFFSET)*32u))))

/********************************************************************************************
************************************** 26 DMACHMAP3 *********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMACHMAP3       (((BITBANDING_DMACHMAP3_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMACHMAP3_OFFSET)*32u))))

/********************************************************************************************
************************************** 27 DMAPeriphID0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPeriphID0       (((BITBANDING_DMAPeriphID0_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPeriphID0_OFFSET)*32u))))

/********************************************************************************************
************************************** 28 DMAPeriphID1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPeriphID1       (((BITBANDING_DMAPeriphID1_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPeriphID1_OFFSET)*32u))))

/********************************************************************************************
************************************** 29 DMAPeriphID2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPeriphID2       (((BITBANDING_DMAPeriphID2_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPeriphID2_OFFSET)*32u))))

/********************************************************************************************
************************************** 30 DMAPeriphID3 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPeriphID3       (((BITBANDING_DMAPeriphID3_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPeriphID3_OFFSET)*32u))))

/********************************************************************************************
************************************** 31 DMAPeriphID4 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPeriphID4       (((BITBANDING_DMAPeriphID4_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPeriphID4_OFFSET)*32u))))

/********************************************************************************************
************************************** 32 DMAPCellID0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPCellID0       (((BITBANDING_DMAPCellID0_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPCellID0_OFFSET)*32u))))

/********************************************************************************************
************************************** 33 DMAPCellID1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPCellID1       (((BITBANDING_DMAPCellID1_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPCellID1_OFFSET)*32u))))

/********************************************************************************************
************************************** 34 DMAPCellID2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPCellID2       (((BITBANDING_DMAPCellID2_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPCellID2_OFFSET)*32u))))

/********************************************************************************************
************************************** 35 DMAPCellID3 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_DMAPCellID3       (((BITBANDING_DMAPCellID3_TypeDef*)(DMA_BITBANDING_BASE+((DMA_OFFSET+DMA_DMAPCellID3_OFFSET)*32u))))

#endif /* XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_ */
