/**
 *
 * @file DMA_RegisterPeripheral_Bitbanding.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 28 jul. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description * 28 jul. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_
#define XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_

#include <xDriver_MCU/DMA/Peripheral/Register/xHeader/DMA_RegisterAddress.h>
#include <xDriver_MCU/DMA/Peripheral/Register/RegisterDefines/DMA_RegisterDefines.h>
#include <xDriver_MCU/DMA/Peripheral/Struct/xHeader/DMA_StructPeripheral_Bitbanding.h>

#define DMA_BITBANDING    ((DMA_BITBANDING_TypeDef*) (DMA_BITBANDING_BASE + (DMA_OFFSET * 32UL)))

/********************************************************************************************
************************************** 4 STAT **********************************************
********************************************************************************************/
#define DMA_BITBANDING_STAT    ((BITBANDING_DMASTAT_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_STAT_OFFSET) * 32UL)))

#define DMA_BITBANDING_STAT_MASTEN    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_STAT_OFFSET) * 32UL) + (DMA_STAT_R_MASTEN_BIT * 4UL))))

/********************************************************************************************
************************************** 5 CFG **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CFG    ((BITBANDING_DMACFG_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CFG_OFFSET) * 32UL)))

#define DMA_BITBANDING_CFG_MASTEN    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CFG_OFFSET) * 32UL) + (DMA_CFG_R_MASTEN_BIT * 4UL))))

/********************************************************************************************
************************************** 6 CTLBASE **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CTLBASE    ((BITBANDING_DMACTLBASE_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CTLBASE_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 7 ALTBASE **********************************************
********************************************************************************************/
#define DMA_BITBANDING_ALTBASE    ((BITBANDING_DMAALTBASE_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTBASE_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 8 WAITSTAT **********************************************
********************************************************************************************/
#define DMA_BITBANDING_WAITSTAT    ((BITBANDING_DMAWAITSTAT_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL)))

#define DMA_BITBANDING_WAITSTAT_WAITREQ0    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ0_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ1    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ1_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ2    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ2_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ3    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ3_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ4    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ4_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ5    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ5_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ6    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ6_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ7    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ7_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ8    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ8_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ9    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ9_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ10    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ10_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ11    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ11_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ12    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ12_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ13    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ13_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ14    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ14_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ15    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ15_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ16    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ16_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ17    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ17_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ18    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ18_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ19    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ19_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ20    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ20_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ21    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ21_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ22    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ22_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ23    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ23_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ24    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ24_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ25    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ25_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ26    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ26_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ27    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ27_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ28    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ28_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ29    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ29_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ30    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ30_BIT * 4UL))))
#define DMA_BITBANDING_WAITSTAT_WAITREQ31    (*((volatile const uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_WAITSTAT_OFFSET) * 32UL) + (DMA_WAITSTAT_R_WAITREQ31_BIT * 4UL))))

/********************************************************************************************
************************************** 9 SWREQ **********************************************
********************************************************************************************/
#define DMA_BITBANDING_SWREQ    ((BITBANDING_DMASWREQ_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL)))

#define DMA_BITBANDING_SWREQ_SWREQ0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ0_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ1_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ2_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ3_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ4_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ5_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ6_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ7_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ8_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ9_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ10_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ11_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ12_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ13_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ14_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ15_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ16_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ17_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ18_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ19_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ20_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ21_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ22_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ23_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ24_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ25_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ26_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ27_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ28_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ29_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ30_BIT * 4UL))))
#define DMA_BITBANDING_SWREQ_SWREQ31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_SWREQ_OFFSET) * 32UL) + (DMA_SWREQ_R_SWREQ31_BIT * 4UL))))

/********************************************************************************************
************************************** 10 USEBURSTSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_USEBURSTSET    ((BITBANDING_DMASET_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL)))

#define DMA_BITBANDING_USEBURSTSET_SET0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTSET_SET31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTSET_OFFSET) * 32UL) + (DMA_USEBURSTSET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 11 USEBURSTCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_USEBURSTCLR    ((BITBANDING_DMACLR_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_USEBURSTCLR_CLR0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_USEBURSTCLR_CLR31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_USEBURSTCLR_OFFSET) * 32UL) + (DMA_USEBURSTCLR_R_CLR31_BIT * 4UL))))

/********************************************************************************************
************************************** 12 REQMASKSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_REQMASKSET    ((BITBANDING_DMASET_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL)))

#define DMA_BITBANDING_REQMASKSET_SET0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKSET_SET31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKSET_OFFSET) * 32UL) + (DMA_REQMASKSET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 13 REQMASKCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_REQMASKCLR    ((BITBANDING_DMACLR_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_REQMASKCLR_CLR0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_REQMASKCLR_CLR31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_REQMASKCLR_OFFSET) * 32UL) + (DMA_REQMASKCLR_R_CLR31_BIT * 4UL))))


/********************************************************************************************
************************************** 14 ENASET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_ENASET    ((BITBANDING_DMASET_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL)))

#define DMA_BITBANDING_ENASET_SET0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_ENASET_SET31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENASET_OFFSET) * 32UL) + (DMA_ENASET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 15 ENACLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_ENACLR    ((BITBANDING_DMACLR_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_ENACLR_CLR0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_ENACLR_CLR31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ENACLR_OFFSET) * 32UL) + (DMA_ENACLR_R_CLR31_BIT * 4UL))))

/********************************************************************************************
************************************** 16 ALTSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_ALTSET    ((BITBANDING_DMASET_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL)))

#define DMA_BITBANDING_ALTSET_SET0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_ALTSET_SET31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTSET_OFFSET) * 32UL) + (DMA_ALTSET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 17 ALTCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_ALTCLR    ((BITBANDING_DMACLR_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_ALTCLR_CLR0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_ALTCLR_CLR31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ALTCLR_OFFSET) * 32UL) + (DMA_ALTCLR_R_CLR31_BIT * 4UL))))

/********************************************************************************************
************************************* 18 PRIOSET **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PRIOSET    ((BITBANDING_DMASET_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL)))

#define DMA_BITBANDING_PRIOSET_SET0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET0_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET1_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET2_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET3_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET4_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET5_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET6_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET7_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET8_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET9_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET10_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET11_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET12_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET13_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET14_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET15_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET16_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET17_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET18_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET19_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET20_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET21_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET22_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET23_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET24_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET25_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET26_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET27_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET28_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET29_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET30_BIT * 4UL))))
#define DMA_BITBANDING_PRIOSET_SET31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOSET_OFFSET) * 32UL) + (DMA_PRIOSET_R_SET31_BIT * 4UL))))

/********************************************************************************************
************************************** 19 PRIOCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PRIOCLR    ((BITBANDING_DMACLR_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_PRIOCLR_CLR0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR0_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR1_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR2_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR3_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR4_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR5_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR6_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR7_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR8_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR9_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR10_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR11_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR12_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR13_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR14_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR15_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR16_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR17_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR18_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR19_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR20_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR21_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR22_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR23_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR24_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR25_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR26_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR27_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR28_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR29_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR30_BIT * 4UL))))
#define DMA_BITBANDING_PRIOCLR_CLR31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PRIOCLR_OFFSET) * 32UL) + (DMA_PRIOCLR_R_CLR31_BIT * 4UL))))

/********************************************************************************************
************************************** 20 ERRCLR **********************************************
********************************************************************************************/
#define DMA_BITBANDING_ERRCLR    ((BITBANDING_DMAERRCLR_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ERRCLR_OFFSET) * 32UL)))

#define DMA_BITBANDING_ERRCLR_ERRCLR    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_ERRCLR_OFFSET) * 32UL) + (DMA_ERRCLR_R_ERRCLR_BIT * 4UL))))

/********************************************************************************************
************************************** 21 CHASGN **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CHASGN    ((BITBANDING_DMACHASGN_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL)))

#define DMA_BITBANDING_CHASGN_CHASGN0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN0_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN1_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN2_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN3_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN4_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN5_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN6_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN7_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN8_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN9_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN10_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN11_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN12_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN13_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN14_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN15_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN16_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN17_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN18_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN19_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN20_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN21_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN22_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN23_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN24_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN25_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN26_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN27_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN28_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN29_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN30_BIT * 4UL))))
#define DMA_BITBANDING_CHASGN_CHASGN31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHASGN_OFFSET) * 32UL) + (DMA_CHASGN_R_CHASGN31_BIT * 4UL))))

/********************************************************************************************
************************************** 22 CHIS **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CHIS    ((BITBANDING_DMACHIS_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL)))

#define DMA_BITBANDING_CHIS_CHIS0    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS0_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS1    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS1_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS2    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS2_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS3    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS3_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS4    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS4_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS5    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS5_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS6    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS6_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS7    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS7_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS8    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS8_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS9    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS9_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS10    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS10_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS11    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS11_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS12    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS12_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS13    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS13_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS14    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS14_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS15    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS15_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS16    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS16_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS17    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS17_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS18    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS18_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS19    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS19_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS20    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS20_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS21    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS21_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS22    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS22_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS23    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS23_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS24    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS24_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS25    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS25_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS26    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS26_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS27    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS27_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS28    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS28_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS29    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS29_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS30    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS30_BIT * 4UL))))
#define DMA_BITBANDING_CHIS_CHIS31    (*((volatile uint32_t *) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHIS_OFFSET) * 32UL) + (DMA_CHIS_R_CHIS31_BIT * 4UL))))

/********************************************************************************************
************************************** 23 CHMAP0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CHMAP0    ((BITBANDING_DMACHMAP0_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHMAP0_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 24 CHMAP1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CHMAP1    ((BITBANDING_DMACHMAP1_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHMAP1_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 25 CHMAP2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_CHMAP2    ((BITBANDING_DMACHMAP2_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHMAP2_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 26 CHMAP3 *********************************************
********************************************************************************************/
#define DMA_BITBANDING_CHMAP3    ((BITBANDING_DMACHMAP3_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_CHMAP3_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 27 PeriphID0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID0    ((BITBANDING_DMAPeriphID0_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID0_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 28 PeriphID1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID1    ((BITBANDING_DMAPeriphID1_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID1_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 29 PeriphID2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID2    ((BITBANDING_DMAPeriphID2_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID2_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 30 PeriphID3 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID3    ((BITBANDING_DMAPeriphID3_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID3_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 31 PeriphID4 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PeriphID4    ((BITBANDING_DMAPeriphID4_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PeriphID4_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 32 PCellID0 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PCellID0    ((BITBANDING_DMAPCellID0_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PCellID0_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 33 PCellID1 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PCellID1    ((BITBANDING_DMAPCellID1_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PCellID1_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 34 PCellID2 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PCellID2    ((BITBANDING_DMAPCellID2_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PCellID2_OFFSET) * 32UL)))

/********************************************************************************************
************************************** 35 PCellID3 **********************************************
********************************************************************************************/
#define DMA_BITBANDING_PCellID3    ((BITBANDING_DMAPCellID3_TypeDef*) (DMA_BITBANDING_BASE + ((DMA_OFFSET + DMA_PCellID3_OFFSET) * 32UL)))

#endif /* XDRIVER_MCU_DRIVER_HEADER_DMA_DMA_PERIPHERAL_DMA_REGISTER_DMA_REGISTERPERIPHERAL_BITBANDING_H_ */
