/*
 * SYSTICK_Enum.h
 *
 *  Created on: 18 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_PERIPHERAL_SYSTICK_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_PERIPHERAL_SYSTICK_ENUM_H_

#include <xUtils/Standard/Standard.h>

typedef enum
{
    SYSTICK_enOK = 0UL,
    SYSTICK_enERROR = 1UL,
}SYSTICK_nSTATUS;

typedef enum
{
    SYSTICK_enENABLE_DIS = 0UL,
    SYSTICK_enENABLE_ENA = 1UL,
}SYSTICK_nENABLE;

typedef enum
{
    SYSTICK_enPRI0 = 0UL,
    SYSTICK_enPRI1 = 1UL,
    SYSTICK_enPRI2 = 2UL,
    SYSTICK_enPRI3 = 3UL,
    SYSTICK_enPRI4 = 4UL,
    SYSTICK_enPRI5 = 5UL,
    SYSTICK_enPRI6 = 6UL,
    SYSTICK_enPRI7 = 7UL,
    SYSTICK_enDEFAULT = 0xFFFFFFFFUL,
}SYSTICK_nPRIORITY;

typedef enum
{
    SYSTICK_enINT_NOOCCUR = 0UL,
    SYSTICK_enINT_OCCUR = 1UL,
} SYSTICK_nINT_STATUS;

typedef enum
{
    SYSTICK_enPIOSC4 = 0UL,
    SYSTICK_enSYSCLK = 1UL,
}SYSTICK_nCLKSOURCE;

#endif /* XDRIVER_MCU_DRIVER_HEADER_SYSTICK_SYSTICK_PERIPHERAL_SYSTICK_ENUM_H_ */
