/*
 * FPU_Enum.h
 *
 *  Created on: 17 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_


typedef enum
{
    FPU_enOK =0u,
    FPU_enERROR =1u,
}FPU_nSTATUS;

typedef enum
{
    FPU_enDENIED =0u,
    FPU_enONLY_PRIVILEGED =1u,
    FPU_enFULL_ACCESS =3u,
}FPU_nACCESS;

typedef enum
{
    FPU_enLAZY_PRESERVATION_DIS =0u,
    FPU_enLAZY_PRESERVATION_EN =1u,
}FPU_nLAZY_PRESERVATION;

typedef enum
{
    FPU_enAUTO_PRESERVATION_DIS =0u,
    FPU_enAUTO_PRESERVATION_EN =1u,
}FPU_nAUTO_PRESERVATION;

typedef enum
{
    FPU_enPRESERVATION_NOACTIVE =0u,
    FPU_enPRESERVATION_ACTIVE =1u,
}FPU_nPRESERVATION_STATUS;

typedef enum
{
    FPU_enHALF_PRECISION_IEEE =0u,
    FPU_enHALF_PRECISION_ALT =1u,
}FPU_nHALF_PRECISION;

typedef enum
{
    FPU_enNAN_PROPAGATE =0u,
    FPU_enNAN_NAN =1u,
}FPU_nNAN;

typedef enum
{
    FPU_enROUNDING_NEAREST =0u,
    FPU_enROUNDING_PLUSINF =1u,
    FPU_enROUNDING_MINUSINF =2u,
    FPU_enROUNDING_ZERO =3u,
}FPU_nROUNDING;

typedef enum
{
    FPU_enEXCEPTION_DENORMAL=0x80u,
    FPU_enEXCEPTION_INEXACT=0x10u,
    FPU_enEXCEPTION_UNDERFLOW=0x08u,
    FPU_enEXCEPTION_OVERFLOW=0x04u,
    FPU_enEXCEPTION_DIV0=0x02u,
    FPU_enEXCEPTION_INVALID=0x01u,
}FPU_nEXCEPTION;



#endif /* XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_ */
