/*
 * FPU_Enum.h
 *
 *  Created on: 17 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_


typedef enum
{
    FPU_enOK =0,
    FPU_enERROR =1,
}FPU_nSTATUS;

typedef enum
{
    FPU_enDENIED =0,
    FPU_enONLY_PRIVILEGED =1,
    FPU_enFULL_ACCESS =3,
}FPU_nACCESS;

typedef enum
{
    FPU_enLAZY_PRESERVATION_DIS =0,
    FPU_enLAZY_PRESERVATION_EN =1,
}FPU_nLAZY_PRESERVATION;

typedef enum
{
    FPU_enAUTO_PRESERVATION_DIS =0,
    FPU_enAUTO_PRESERVATION_EN =1,
}FPU_nAUTO_PRESERVATION;

typedef enum
{
    FPU_enPRESERVATION_NOACTIVE =0,
    FPU_enPRESERVATION_ACTIVE =1,
}FPU_nPRESERVATION_STATUS;

typedef enum
{
    FPU_enHALF_PRECISION_IEEE =0,
    FPU_enHALF_PRECISION_ALT =1,
}FPU_nHALF_PRECISION;

typedef enum
{
    FPU_enNAN_PROPAGATE =0,
    FPU_enNAN_NAN =1,
}FPU_nNAN;

typedef enum
{
    FPU_enROUNDING_NEAREST =0,
    FPU_enROUNDING_PLUSINF =1,
    FPU_enROUNDING_MINUSINF =2,
    FPU_enROUNDING_ZERO =3,
}FPU_nROUNDING;

typedef enum
{
    FPU_enEXCEPTION_DENORMAL=0x80,
    FPU_enEXCEPTION_INEXACT=0x10,
    FPU_enEXCEPTION_UNDERFLOW=0x08,
    FPU_enEXCEPTION_OVERFLOW=0x04,
    FPU_enEXCEPTION_DIV0=0x02,
    FPU_enEXCEPTION_INVALID=0x01,
}FPU_nEXCEPTION;



#endif /* XDRIVER_MCU_DRIVER_HEADER_FPU_FPU_PERIPHERAL_FPU_ENUM_H_ */
