/*
 * FLASH_Enum.h
 *
 *  Created on: 16 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_FLASH_FLASH_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_FLASH_FLASH_ENUM_H_

typedef enum
{
    FLASH_enOK =0u,
    FLASH_enERROR=1u,
}FLASH_nSTATUS;


typedef enum
{
    FLASH_enINTERRUPT_ACCESS=0u,
    FLASH_enINTERRUPT_PROGRAMMING=1u,
    FLASH_enINTERRUPT_EEPROM=2u,
    FLASH_enINTERRUPT_PUMP_VOL=3u,
    FLASH_enINTERRUPT_INVALID_DATA=4u,
    FLASH_enINTERRUPT_ERRASE_ERROR=5u,
    FLASH_enINTERRUPT_PROGRAM_ERROR=6u,
    FLASH_enINTERRUPT_MAX=6u,
}FLASH_nINTERRUPT;

typedef enum
{
    FLASH_enINT_ACCESS      =0x01u,
    FLASH_enINT_PROGRAMMING =0x02u,
    FLASH_enINT_EEPROM      =0x04u,

    FLASH_enINT_PUMP_VOL    =0x200u,
    FLASH_enINT_INVALID_DATA=0x400u,
    FLASH_enINT_ERRASE_ERROR=0x800u,
    FLASH_enINT_PROGRAM_ERROR=0x2000u,
    FLASH_enINT_ALL         =0x2E07u,
    FLASH_enINT_UNDEF       =0xFFFFFu,
}FLASH_nINT;

typedef enum
{
    FLASH_enINT_NOOCCUR=0u,
    FLASH_enINT_OCCUR=1u,
    FLASH_enINT_STATUS_UNDEF=0xFFu,
}FLASH_nINT_STATUS;

typedef enum
{
    FLASH_enPRI0=0u,
    FLASH_enPRI1=1u,
    FLASH_enPRI2=2u,
    FLASH_enPRI3=3u,
    FLASH_enPRI4=4u,
    FLASH_enPRI5=5u,
    FLASH_enPRI6=6u,
    FLASH_enPRI7=7u,
    FLASH_enDEFAULT=0xFFu,
}FLASH_nPRIORITY;

#endif /* XDRIVER_MCU_DRIVER_HEADER_FLASH_FLASH_ENUM_H_ */
