/*
 * FLASH_Enum.h
 *
 *  Created on: 16 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_FLASH_FLASH_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_FLASH_FLASH_ENUM_H_

typedef enum
{
    FLASH_enOK =0U,
    FLASH_enERROR=1U,
}FLASH_nSTATUS;


typedef enum
{
    FLASH_enINTERRUPT_ACCESS=0U,
    FLASH_enINTERRUPT_PROGRAMMING=1U,
    FLASH_enINTERRUPT_EEPROM=2U,
    FLASH_enINTERRUPT_PUMP_VOL=3U,
    FLASH_enINTERRUPT_INVALID_DATA=4U,
    FLASH_enINTERRUPT_ERRASE_ERROR=5U,
    FLASH_enINTERRUPT_PROGRAM_ERROR=6U,
    FLASH_enINTERRUPT_MAX=6U,
}FLASH_nINTERRUPT;

typedef enum
{
    FLASH_enINT_ACCESS      =0x01U,
    FLASH_enINT_PROGRAMMING =0x02U,
    FLASH_enINT_EEPROM      =0x04U,

    FLASH_enINT_PUMP_VOL    =0x200U,
    FLASH_enINT_INVALID_DATA=0x400U,
    FLASH_enINT_ERRASE_ERROR=0x800U,
    FLASH_enINT_PROGRAM_ERROR=0x2000U,
    FLASH_enINT_ALL         =0x2E07U,
    FLASH_enINT_UNDEF       =0xFFFFFU,
}FLASH_nINT;

typedef enum
{
    FLASH_enINT_NOOCCUR=0U,
    FLASH_enINT_OCCUR=1U,
    FLASH_enINT_STATUS_UNDEF=0xFFFFFFFFU,
}FLASH_nINT_STATUS;

typedef enum
{
    FLASH_enPRI0=0U,
    FLASH_enPRI1=1U,
    FLASH_enPRI2=2U,
    FLASH_enPRI3=3U,
    FLASH_enPRI4=4U,
    FLASH_enPRI5=5U,
    FLASH_enPRI6=6U,
    FLASH_enPRI7=7U,
    FLASH_enDEFAULT=0xFFFFFFFFU,
}FLASH_nPRIORITY;

#endif /* XDRIVER_MCU_DRIVER_HEADER_FLASH_FLASH_ENUM_H_ */
