

/**
 * main.c
 */

#include "stdlib.h"
#include "SCB.h"
#include "FPU.h"
#include "MPU.h"
#include "SYSTICK.h"
#include "SYSEXC.h"
#include "HIB.h"
#include "SYSCTL.h"
#include "NVIC.h"
#include "EEPROM.h"
#include "FLASH.h"
//#include "UDMA.h"
#include "GPIO.h"


//uint32_t pu32Array[14]={0,1,2,3,4,5,6,7,8,9,10,11,0xAA55CFDA,0x11223344};
uint32_t pu32Array[14]={0};
uint32_t pu32Array1[14]={0xBF00,1,2,3,4,5,6,7,8,9,10,11,0xAA55CFDA,0x11223344};
void main(void)
{
    volatile uint32_t memory=0;
    volatile uint32_t u32ValueSW=0;
    volatile uint32_t u32Memory=0;
    volatile uint16_t u16Memory=0;
    volatile uint8_t u8Memory=0;

    __asm(" cpsie i");
    FPU__vInit();
    MPU__vInit();
    SCB__vInit();
    SYSEXC__vInit((SYSEXC_nINTERRUPT)(SYSEXC_enINVALID|SYSEXC_enDIV0|
            SYSEXC_enOVERFLOW|SYSEXC_enUNDERFLOW));
    SYSCTL__enInit(); // system clock 80MHz
    SysTick__enInitUs(10,SCB_enSHPR0);
    EEPROM__enInit();

    SYSCTL__vResetPeripheral(SYSCTL_enGPIOF);
    SYSCTL__vDisRunModePeripheral(SYSCTL_enGPIOF);
    SYSCTL__vEnRunModePeripheral(SYSCTL_enGPIOF);

    //GREEN LED
    GPIO_AHB->AHB[5].GPIODIR|=GPIO_GPIODIR_R_DIR3_OUTPUT;
    GPIO_AHB->AHB[5].GPIOAMSEL&=~GPIO_GPIOAMSEL_R_AMSEL3_MASK;
    GPIO_AHB->AHB[5].GPIODR2R|=GPIO_GPIODR2R_R_DRV23_MASK;
    GPIO_AHB->AHB[5].GPIOODR&=~GPIO_GPIOODR_R_ODE3_MASK;

    GPIO_AHB->AHB[5].GPIOAFSEL&=~GPIO_GPIOAFSEL_R_AFSEL3_MASK;
    GPIO_AHB->AHB[5].GPIOPDR&=~GPIO_GPIOPDR_R_PDE3_MASK;
    GPIO_AHB->AHB[5].GPIOPUR&=~GPIO_GPIOPUR_R_PUE3_MASK;
    GPIO_AHB->AHB[5].GPIODEN|=GPIO_GPIODEN_R_DEN3_EN;

    //BLUE LED
    GPIO_AHB_BITBANDING->AHB[5].GPIODIR[2]=GPIO_GPIODIR_DIR2_OUTPUT;
    GPIO_AHB_BITBANDING->AHB[5].GPIOAMSEL[2]=GPIO_GPIOAMSEL_AMSEL2_DIS;
    GPIO_AHB_BITBANDING->AHB[5].GPIODR2R[2]=GPIO_GPIODR2R_DRV22_EN;
    GPIO_AHB_BITBANDING->AHB[5].GPIOODR[2]=GPIO_GPIOODR_ODE2_PP;

    GPIO_AHB_BITBANDING->AHB[5].GPIOPDR[2]=GPIO_GPIOPDR_PDE2_DIS;
    GPIO_AHB_BITBANDING->AHB[5].GPIOPUR[2]=GPIO_GPIOPUR_PUE2_DIS;
    GPIO_AHB_BITBANDING->AHB[5].GPIOAFSEL[2]=GPIO_GPIOAFSEL_AFSEL2_GPIO;
    GPIO_AHB_BITBANDING->AHB[5].GPIODEN[2]=GPIO_GPIODEN_DEN2_EN;

    //RED LED
    GPIOF_AHB->GPIODIR|=GPIO_GPIODIR_R_DIR1_OUTPUT;
    GPIOF_AHB->GPIOAMSEL&=~GPIO_GPIOAMSEL_R_AMSEL1_MASK;
    GPIOF_AHB->GPIODR2R|=GPIO_GPIODR2R_R_DRV21_MASK;
    GPIOF_AHB->GPIOODR&=~GPIO_GPIOODR_R_ODE1_MASK;

    GPIOF_AHB->GPIOPDR&=~GPIO_GPIOPDR_R_PDE1_MASK;
    GPIOF_AHB->GPIOPUR&=~GPIO_GPIOPUR_R_PUE1_MASK;
    GPIOF_AHB->GPIOAFSEL&=~GPIO_GPIOAFSEL_R_AFSEL1_MASK;
    GPIOF_AHB->GPIODEN|=GPIO_GPIODEN_R_DEN1_EN;

    //SW1
    GPIOF_AHB_BITBANDING->GPIODIR[4]=GPIO_GPIODIR_DIR4_INPUT;
    GPIOF_AHB_BITBANDING->GPIOAMSEL[4]=GPIO_GPIOAMSEL_AMSEL4_DIS;
    GPIOF_AHB_BITBANDING->GPIODR2R[4]=GPIO_GPIODR2R_DRV24_EN;
    GPIOF_AHB_BITBANDING->GPIOODR[4]=GPIO_GPIOODR_ODE4_OD;

    GPIOF_AHB_BITBANDING->GPIOPDR[4]=GPIO_GPIOPDR_PDE4_DIS;
    GPIOF_AHB_BITBANDING->GPIOPUR[4]=GPIO_GPIOPUR_PUE4_EN;
    GPIOF_AHB_BITBANDING->GPIOAFSEL[4]=GPIO_GPIOAFSEL_AFSEL4_GPIO;
    GPIOF_AHB_BITBANDING->GPIODEN[4]=GPIO_GPIODEN_DEN4_EN;

    //SW2
    GPIOF_AHB_GPIODIR_BITBANDING->DIR0 =GPIO_GPIODIR_DIR0_INPUT;
    GPIOF_AHB_GPIOAMSEL_BITBANDING->AMSEL0 =GPIO_GPIOAMSEL_AMSEL0_DIS;
    GPIOF_AHB_GPIODR2R_BITBANDING->DRV20 =GPIO_GPIODR2R_DRV20_EN;
    GPIOF_AHB_GPIOODR_BITBANDING->ODE0 =GPIO_GPIOODR_ODE0_OD;

    GPIOF_AHB_GPIOLOCK_R=GPIO_GPIOLOCK_R_LOCK_KEY;
    GPIOF_AHB_GPIOCR_BITBANDING->CR0 =GPIO_GPIOCR_CR0_EN;
    GPIOF_AHB_GPIOPDR_BITBANDING->PDE0 =GPIO_GPIOPDR_PDE0_DIS;
    GPIOF_AHB_GPIOPUR_BITBANDING->PUE0 =GPIO_GPIOPUR_PUE0_EN;
    GPIOF_AHB_GPIOAFSEL_BITBANDING->AFSEL0 =GPIO_GPIOAFSEL_AFSEL0_GPIO;
    GPIOF_AHB_GPIODEN_BITBANDING->DEN0 =GPIO_GPIODEN_DEN0_EN;


    GPIOF_AHB->GPIODATA&=~GPIO_GPIODATA_R_DATA1_MASK;
    GPIO_AHB_BITBANDING->AHB[5].GPIODATA[2]=GPIO_GPIODATA_DATA2_LOW;
    GPIO_AHB->AHB[5].GPIODATA|=GPIO_GPIODATA_R_DATA3_HIGH;
    //HIB__enInit(10,0);
    memory=0;
    while(1)
    {
        SysTick__vDelayUs(100000);
        memory++;

        if((memory&1)==0)
        {
            GPIO_AHB->AHB[5].GPIODATA_MASK[GPIO_GPIODATA_R_DATA3_MASK]=GPIO_GPIODATA_R_DATA3_LOW;
        }
        else
        {
            GPIO_AHB->AHB[5].GPIODATA_MASK[GPIO_GPIODATA_R_DATA3_MASK]=GPIO_GPIODATA_R_DATA3_HIGH;
        }


        u32ValueSW=GPIOF_AHB_BITBANDING->GPIODATA[4];
        if(u32ValueSW !=0)
        {
            GPIOF_AHB->GPIODATA_MASK[GPIO_GPIODATA_R_DATA1_MASK]=GPIO_GPIODATA_R_DATA1_LOW;
        }
        else
        {
            GPIOF_AHB->GPIODATA_MASK[GPIO_GPIODATA_R_DATA1_MASK]=GPIO_GPIODATA_R_DATA1_HIGH;
        }

        u32ValueSW=GPIOF_AHB_GPIODATA_BITBANDING->DATA0;
        u32ValueSW^=1;
        GPIO_AHB_BITBANDING->AHB[5].GPIODATA[2]=u32ValueSW;

    }
}
