/*
 * EEPROM_Dependencies.h
 *
 *  Created on: 16 jun. 2020
 *      Author: vyldram
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_EEPROM_EEPROM_DEPENDENCIES_H_
#define XDRIVER_MCU_DRIVER_HEADER_EEPROM_EEPROM_DEPENDENCIES_H_

#include <xDriver_MCU/SYSCTL/SYSCTL.h>
#include <xDriver_MCU/FLASH/FLASH.h>


#endif /* XDRIVER_MCU_DRIVER_HEADER_EEPROM_EEPROM_DEPENDENCIES_H_ */
