/**
 *
 * @file GPIO_RegisterPeripheral_AHB_Bitbanding_ModuleC.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 28 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description * 28 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_GPIO_GPIO_PERIPHERAL_GPIO_REGISTER_GPIO_REGISTERPERIPHERAL_BITBANDING_GPIO_REGISTERPERIPHERAL_AHB_BITBANDING_GPIO_REGISTERPERIPHERAL_AHB_BITBANDING_MODULEC_H_
#define XDRIVER_MCU_DRIVER_HEADER_GPIO_GPIO_PERIPHERAL_GPIO_REGISTER_GPIO_REGISTERPERIPHERAL_BITBANDING_GPIO_REGISTERPERIPHERAL_AHB_BITBANDING_GPIO_REGISTERPERIPHERAL_AHB_BITBANDING_MODULEC_H_

#include <xDriver_MCU/GPIO/Peripheral/Register/xHeader/GPIO_RegisterAddress.h>
#include <xDriver_MCU/GPIO/Peripheral/Register/RegisterDefines/GPIO_RegisterDefines.h>
#include <xDriver_MCU/GPIO/Peripheral/Struct/xHeader/GPIO_StructPeripheral_Bitbanding.h>

#define GPIOC_AHB_BITBANDING    ((GPIO_BITBANDING_TypeDef*) (GPIO_BITBANDING_BASE + (GPIOC_AHB_OFFSET * 32UL)))
#define GPIOC_AHB_AUX_BITBANDING    ((GPIO_AUX_BITBANDING_TypeDef*) (GPIO_BITBANDING_BASE + (GPIOC_AHB_OFFSET * 32UL)))

/******************************************************************************************
 *********************************** * 1 GPIODATA *********************************************
 ******************************************************************************************/

/* GPIOC AHB DATA*/
#define GPIOC_AHB_BITBANDING_GPIODATA_MASK    ((BITBANDING_GPIODATA_MASK_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_MASK_OFFSET) * 32UL)))
#define GPIOC_AHB_BITBANDING_GPIODATA    ((BITBANDING_GPIODATA_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL)))

/* GPIOC AHB DATA BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIODATA0_MASK_DATA0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA0_MASK_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA1_MASK_DATA1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA1_MASK_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA2_MASK_DATA2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA2_MASK_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA3_MASK_DATA3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA3_MASK_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA4_MASK_DATA4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA4_MASK_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA5_MASK_DATA5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA5_MASK_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA6_MASK_DATA6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA6_MASK_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA7_MASK_DATA7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA7_MASK_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA7_BIT * 4UL))))

#define GPIOC_AHB_BITBANDING_GPIODATA_DATA0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA_DATA1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA_DATA2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA_DATA3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA_DATA4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA_DATA5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA_DATA6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODATA_DATA7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODATA_OFFSET) * 32UL) + (GPIO_GPIODATA_R_DATA7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 2 GPIODIR *********************************************
 ******************************************************************************************/
/* GPIOC AHB DIR*/
#define GPIOC_AHB_BITBANDING_GPIODIR    ((BITBANDING_GPIODIR_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL)))

/* GPIOC AHB DIR BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIODIR_DIR0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL) + (GPIO_GPIODIR_R_DIR0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODIR_DIR1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL) + (GPIO_GPIODIR_R_DIR1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODIR_DIR2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL) + (GPIO_GPIODIR_R_DIR2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODIR_DIR3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL) + (GPIO_GPIODIR_R_DIR3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODIR_DIR4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL) + (GPIO_GPIODIR_R_DIR4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODIR_DIR5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL) + (GPIO_GPIODIR_R_DIR5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODIR_DIR6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL) + (GPIO_GPIODIR_R_DIR6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODIR_DIR7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODIR_OFFSET) * 32UL) + (GPIO_GPIODIR_R_DIR7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 3 GPIOIS *********************************************
 ******************************************************************************************/
/* GPIOC AHB IS*/
#define GPIOC_AHB_BITBANDING_GPIOIS    ((BITBANDING_GPIOIS_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL)))

/* GPIOC AHB IS BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOIS_IS0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL) + (GPIO_GPIOIS_R_IS0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIS_IS1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL) + (GPIO_GPIOIS_R_IS1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIS_IS2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL) + (GPIO_GPIOIS_R_IS2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIS_IS3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL) + (GPIO_GPIOIS_R_IS3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIS_IS4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL) + (GPIO_GPIOIS_R_IS4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIS_IS5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL) + (GPIO_GPIOIS_R_IS5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIS_IS6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL) + (GPIO_GPIOIS_R_IS6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIS_IS7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIS_OFFSET) * 32UL) + (GPIO_GPIOIS_R_IS7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 4 GPIOIBE *********************************************
 ******************************************************************************************/
/* GPIOC AHB IBE*/
#define GPIOC_AHB_BITBANDING_GPIOIBE    ((BITBANDING_GPIOIBE_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL)))

/* GPIOC AHB IBE BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOIBE_IBE0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL) + (GPIO_GPIOIBE_R_IBE0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIBE_IBE1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL) + (GPIO_GPIOIBE_R_IBE1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIBE_IBE2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL) + (GPIO_GPIOIBE_R_IBE2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIBE_IBE3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL) + (GPIO_GPIOIBE_R_IBE3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIBE_IBE4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL) + (GPIO_GPIOIBE_R_IBE4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIBE_IBE5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL) + (GPIO_GPIOIBE_R_IBE5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIBE_IBE6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL) + (GPIO_GPIOIBE_R_IBE6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIBE_IBE7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIBE_OFFSET) * 32UL) + (GPIO_GPIOIBE_R_IBE7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 5 GPIOIEV *********************************************
 ******************************************************************************************/
/* GPIOC AHB IEV*/
#define GPIOC_AHB_BITBANDING_GPIOIEV    ((BITBANDING_GPIOIEV_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL)))

/* GPIOC AHB IEV BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOIEV_IEV0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL) + (GPIO_GPIOIEV_R_IEV0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIEV_IEV1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL) + (GPIO_GPIOIEV_R_IEV1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIEV_IEV2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL) + (GPIO_GPIOIEV_R_IEV2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIEV_IEV3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL) + (GPIO_GPIOIEV_R_IEV3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIEV_IEV4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL) + (GPIO_GPIOIEV_R_IEV4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIEV_IEV5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL) + (GPIO_GPIOIEV_R_IEV5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIEV_IEV6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL) + (GPIO_GPIOIEV_R_IEV6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIEV_IEV7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIEV_OFFSET) * 32UL) + (GPIO_GPIOIEV_R_IEV7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 6 GPIOIM *********************************************
 ******************************************************************************************/
/* GPIOC AHB IME*/
#define GPIOC_AHB_BITBANDING_GPIOIM    ((BITBANDING_GPIOIM_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL)))

/* GPIOC AHB IME BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOIM_IME0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL) + (GPIO_GPIOIM_R_IME0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIM_IME1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL) + (GPIO_GPIOIM_R_IME1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIM_IME2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL) + (GPIO_GPIOIM_R_IME2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIM_IME3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL) + (GPIO_GPIOIM_R_IME3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIM_IME4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL) + (GPIO_GPIOIM_R_IME4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIM_IME5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL) + (GPIO_GPIOIM_R_IME5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIM_IME6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL) + (GPIO_GPIOIM_R_IME6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOIM_IME7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOIM_OFFSET) * 32UL) + (GPIO_GPIOIM_R_IME7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 7 GPIORIS *********************************************
 ******************************************************************************************/
/* GPIOC AHB RIS*/
#define GPIOC_AHB_BITBANDING_GPIORIS    ((BITBANDING_GPIORIS_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL)))

/* GPIOC AHB RIS BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIORIS_RIS0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL) + (GPIO_GPIORIS_R_RIS0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIORIS_RIS1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL) + (GPIO_GPIORIS_R_RIS1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIORIS_RIS2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL) + (GPIO_GPIORIS_R_RIS2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIORIS_RIS3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL) + (GPIO_GPIORIS_R_RIS3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIORIS_RIS4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL) + (GPIO_GPIORIS_R_RIS4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIORIS_RIS5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL) + (GPIO_GPIORIS_R_RIS5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIORIS_RIS6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL) + (GPIO_GPIORIS_R_RIS6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIORIS_RIS7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIORIS_OFFSET) * 32UL) + (GPIO_GPIORIS_R_RIS7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 8 GPIOMIS *********************************************
 ******************************************************************************************/
/* GPIOC AHB MIS*/
#define GPIOC_AHB_BITBANDING_GPIOMIS    ((BITBANDING_GPIOMIS_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL)))

/* GPIOC AHB MIS BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOMIS_MIS0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL) + (GPIO_GPIOMIS_R_MIS0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOMIS_MIS1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL) + (GPIO_GPIOMIS_R_MIS1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOMIS_MIS2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL) + (GPIO_GPIOMIS_R_MIS2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOMIS_MIS3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL) + (GPIO_GPIOMIS_R_MIS3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOMIS_MIS4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL) + (GPIO_GPIOMIS_R_MIS4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOMIS_MIS5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL) + (GPIO_GPIOMIS_R_MIS5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOMIS_MIS6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL) + (GPIO_GPIOMIS_R_MIS6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOMIS_MIS7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOMIS_OFFSET) * 32UL) + (GPIO_GPIOMIS_R_MIS7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 9 GPIOICR *********************************************
 ******************************************************************************************/
/* GPIOC AHB IC*/
#define GPIOC_AHB_BITBANDING_GPIOICR    ((BITBANDING_GPIOICR_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL)))

/* GPIOC AHB IC BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOICR_IC0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL) + (GPIO_GPIOICR_R_IC0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOICR_IC1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL) + (GPIO_GPIOICR_R_IC1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOICR_IC2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL) + (GPIO_GPIOICR_R_IC2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOICR_IC3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL) + (GPIO_GPIOICR_R_IC3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOICR_IC4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL) + (GPIO_GPIOICR_R_IC4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOICR_IC5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL) + (GPIO_GPIOICR_R_IC5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOICR_IC6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL) + (GPIO_GPIOICR_R_IC6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOICR_IC7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOICR_OFFSET) * 32UL) + (GPIO_GPIOICR_R_IC7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 10 GPIOCFSEL *********************************************
 ******************************************************************************************/
/* GPIOC AHB AFSEL*/
#define GPIOC_AHB_BITBANDING_GPIOCFSEL    ((BITBANDING_GPIOCFSEL_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL)))

/* GPIOC AHB AFSEL BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOCFSEL_AFSEL0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL) + (GPIO_GPIOCFSEL_R_AFSEL0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCFSEL_AFSEL1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL) + (GPIO_GPIOCFSEL_R_AFSEL1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCFSEL_AFSEL2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL) + (GPIO_GPIOCFSEL_R_AFSEL2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCFSEL_AFSEL3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL) + (GPIO_GPIOCFSEL_R_AFSEL3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCFSEL_AFSEL4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL) + (GPIO_GPIOCFSEL_R_AFSEL4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCFSEL_AFSEL5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL) + (GPIO_GPIOCFSEL_R_AFSEL5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCFSEL_AFSEL6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL) + (GPIO_GPIOCFSEL_R_AFSEL6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCFSEL_AFSEL7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCFSEL_OFFSET) * 32UL) + (GPIO_GPIOCFSEL_R_AFSEL7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 11 GPIODRR ARRAY *********************************************
 ******************************************************************************************/
/* GPIOC AHB DRV2*/
#define GPIOC_AHB_BITBANDING_GPIODRR    ((BITBANDING_GPIODRR_ARRAY_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 11 GPIODR2R *********************************************
 ******************************************************************************************/
/* GPIOC AHB DRV2*/
#define GPIOC_AHB_BITBANDING_GPIODR2R    ((BITBANDING_GPIODR2R_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL)))

/* GPIOC AHB DRV2 BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIODR2R_DRV20    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL) + (GPIO_GPIODR2R_R_DRV20_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR2R_DRV21    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL) + (GPIO_GPIODR2R_R_DRV21_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR2R_DRV22    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL) + (GPIO_GPIODR2R_R_DRV22_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR2R_DRV23    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL) + (GPIO_GPIODR2R_R_DRV23_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR2R_DRV24    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL) + (GPIO_GPIODR2R_R_DRV24_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR2R_DRV25    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL) + (GPIO_GPIODR2R_R_DRV25_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR2R_DRV26    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL) + (GPIO_GPIODR2R_R_DRV26_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR2R_DRV27    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR2R_OFFSET) * 32UL) + (GPIO_GPIODR2R_R_DRV27_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 12 GPIODR4R *********************************************
 ******************************************************************************************/
/* GPIOC AHB DRV4*/
#define GPIOC_AHB_BITBANDING_GPIODR4R    ((BITBANDING_GPIODR4R_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL)))

/* GPIOC AHB DRV4 BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIODR4R_DRV40    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL) + (GPIO_GPIODR4R_R_DRV40_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR4R_DRV41    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL) + (GPIO_GPIODR4R_R_DRV41_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR4R_DRV42    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL) + (GPIO_GPIODR4R_R_DRV42_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR4R_DRV43    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL) + (GPIO_GPIODR4R_R_DRV43_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR4R_DRV44    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL) + (GPIO_GPIODR4R_R_DRV44_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR4R_DRV45    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL) + (GPIO_GPIODR4R_R_DRV45_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR4R_DRV46    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL) + (GPIO_GPIODR4R_R_DRV46_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR4R_DRV47    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR4R_OFFSET) * 32UL) + (GPIO_GPIODR4R_R_DRV47_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 13 GPIODR8R *********************************************
 ******************************************************************************************/
/* GPIOC AHB DRV8*/
#define GPIOC_AHB_BITBANDING_GPIODR8R    ((BITBANDING_GPIODR8R_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL)))

/* GPIOC AHB DRV8 BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIODR8R_DRV80    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL) + (GPIO_GPIODR8R_R_DRV80_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR8R_DRV81    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL) + (GPIO_GPIODR8R_R_DRV81_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR8R_DRV82    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL) + (GPIO_GPIODR8R_R_DRV82_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR8R_DRV83    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL) + (GPIO_GPIODR8R_R_DRV83_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR8R_DRV84    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL) + (GPIO_GPIODR8R_R_DRV84_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR8R_DRV85    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL) + (GPIO_GPIODR8R_R_DRV85_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR8R_DRV86    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL) + (GPIO_GPIODR8R_R_DRV86_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODR8R_DRV87    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODR8R_OFFSET) * 32UL) + (GPIO_GPIODR8R_R_DRV87_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 14 GPIOODR *********************************************
 ******************************************************************************************/
/* GPIOC AHB ODE*/
#define GPIOC_AHB_BITBANDING_GPIOODR    ((BITBANDING_GPIOODR_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL)))

/* GPIOC AHB ODE BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOODR_ODE0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL) + (GPIO_GPIOODR_R_ODE0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOODR_ODE1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL) + (GPIO_GPIOODR_R_ODE1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOODR_ODE2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL) + (GPIO_GPIOODR_R_ODE2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOODR_ODE3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL) + (GPIO_GPIOODR_R_ODE3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOODR_ODE4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL) + (GPIO_GPIOODR_R_ODE4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOODR_ODE5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL) + (GPIO_GPIOODR_R_ODE5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOODR_ODE6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL) + (GPIO_GPIOODR_R_ODE6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOODR_ODE7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOODR_OFFSET) * 32UL) + (GPIO_GPIOODR_R_ODE7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 15 GPIOPUR *********************************************
 ******************************************************************************************/
/* GPIOC AHB PUE*/
#define GPIOC_AHB_BITBANDING_GPIOPUR    ((BITBANDING_GPIOPUR_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL)))

/* GPIOC AHB PUE BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOPUR_PUE0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL) + (GPIO_GPIOPUR_R_PUE0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPUR_PUE1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL) + (GPIO_GPIOPUR_R_PUE1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPUR_PUE2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL) + (GPIO_GPIOPUR_R_PUE2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPUR_PUE3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL) + (GPIO_GPIOPUR_R_PUE3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPUR_PUE4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL) + (GPIO_GPIOPUR_R_PUE4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPUR_PUE5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL) + (GPIO_GPIOPUR_R_PUE5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPUR_PUE6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL) + (GPIO_GPIOPUR_R_PUE6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPUR_PUE7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPUR_OFFSET) * 32UL) + (GPIO_GPIOPUR_R_PUE7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 16 GPIOPDR *********************************************
 ******************************************************************************************/
/* GPIOC AHB PDE*/
#define GPIOC_AHB_BITBANDING_GPIOPDR    ((BITBANDING_GPIOPDR_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL)))

/* GPIOC AHB PDE BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOPDR_PDE0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL) + (GPIO_GPIOPDR_R_PDE0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPDR_PDE1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL) + (GPIO_GPIOPDR_R_PDE1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPDR_PDE2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL) + (GPIO_GPIOPDR_R_PDE2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPDR_PDE3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL) + (GPIO_GPIOPDR_R_PDE3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPDR_PDE4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL) + (GPIO_GPIOPDR_R_PDE4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPDR_PDE5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL) + (GPIO_GPIOPDR_R_PDE5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPDR_PDE6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL) + (GPIO_GPIOPDR_R_PDE6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOPDR_PDE7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPDR_OFFSET) * 32UL) + (GPIO_GPIOPDR_R_PDE7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 17 GPIOSLR *********************************************
 ******************************************************************************************/
/* GPIOC AHB SLR*/
#define GPIOC_AHB_BITBANDING_GPIOSLR    ((BITBANDING_GPIOSLR_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL)))

/* GPIOC AHB SLR BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOSLR_SLR0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL) + (GPIO_GPIOSLR_R_SLR0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOSLR_SLR1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL) + (GPIO_GPIOSLR_R_SLR1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOSLR_SLR2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL) + (GPIO_GPIOSLR_R_SLR2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOSLR_SLR3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL) + (GPIO_GPIOSLR_R_SLR3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOSLR_SLR4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL) + (GPIO_GPIOSLR_R_SLR4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOSLR_SLR5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL) + (GPIO_GPIOSLR_R_SLR5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOSLR_SLR6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL) + (GPIO_GPIOSLR_R_SLR6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOSLR_SLR7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOSLR_OFFSET) * 32UL) + (GPIO_GPIOSLR_R_SLR7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 18 GPIODEN *********************************************
 ******************************************************************************************/
/* GPIOC AHB DEN*/
#define GPIOC_AHB_BITBANDING_GPIODEN    ((BITBANDING_GPIODEN_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL)))

/* GPIOC AHB DEN BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIODEN_DEN0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL) + (GPIO_GPIODEN_R_DEN0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODEN_DEN1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL) + (GPIO_GPIODEN_R_DEN1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODEN_DEN2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL) + (GPIO_GPIODEN_R_DEN2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODEN_DEN3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL) + (GPIO_GPIODEN_R_DEN3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODEN_DEN4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL) + (GPIO_GPIODEN_R_DEN4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODEN_DEN5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL) + (GPIO_GPIODEN_R_DEN5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODEN_DEN6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL) + (GPIO_GPIODEN_R_DEN6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODEN_DEN7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODEN_OFFSET) * 32UL) + (GPIO_GPIODEN_R_DEN7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 19 GPIOLOCK *********************************************
 ******************************************************************************************/
/* GPIOC AHB LOCK*/
#define GPIOC_AHB_BITBANDING_GPIOLOCK    ((BITBANDING_GPIOLOCK_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOLOCK_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 20 GPIOCR *********************************************
 ******************************************************************************************/
/* GPIOC AHB CR*/
#define GPIOC_AHB_BITBANDING_GPIOCR    ((BITBANDING_GPIOCR_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL)))

/* GPIOC AHB CR BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOCR_CR0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL) + (GPIO_GPIOCR_R_CR0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCR_CR1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL) + (GPIO_GPIOCR_R_CR1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCR_CR2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL) + (GPIO_GPIOCR_R_CR2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCR_CR3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL) + (GPIO_GPIOCR_R_CR3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCR_CR4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL) + (GPIO_GPIOCR_R_CR4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCR_CR5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL) + (GPIO_GPIOCR_R_CR5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCR_CR6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL) + (GPIO_GPIOCR_R_CR6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCR_CR7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCR_OFFSET) * 32UL) + (GPIO_GPIOCR_R_CR7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 21 GPIOCMSEL *********************************************
 ******************************************************************************************/
/* GPIOC AHB AMSEL*/
#define GPIOC_AHB_BITBANDING_GPIOCMSEL    ((BITBANDING_GPIOCMSEL_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL)))

/* GPIOC AHB AMSEL BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOCMSEL_AMSEL0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL) + (GPIO_GPIOCMSEL_R_AMSEL0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCMSEL_AMSEL1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL) + (GPIO_GPIOCMSEL_R_AMSEL1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCMSEL_AMSEL2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL) + (GPIO_GPIOCMSEL_R_AMSEL2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCMSEL_AMSEL3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL) + (GPIO_GPIOCMSEL_R_AMSEL3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCMSEL_AMSEL4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL) + (GPIO_GPIOCMSEL_R_AMSEL4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCMSEL_AMSEL5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL) + (GPIO_GPIOCMSEL_R_AMSEL5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCMSEL_AMSEL6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL) + (GPIO_GPIOCMSEL_R_AMSEL6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCMSEL_AMSEL7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCMSEL_OFFSET) * 32UL) + (GPIO_GPIOCMSEL_R_AMSEL7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 22 GPIOPCTL *********************************************
 ******************************************************************************************/
/* GPIOC AHB PCM*/
#define GPIOC_AHB_BITBANDING_GPIOPCTL    ((BITBANDING_GPIOPCTL_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPCTL_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 23 GPIOCDCCTL *********************************************
 ******************************************************************************************/
/* GPIOC AHB ADCEN*/
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL    ((BITBANDING_GPIOCDCCTL_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL)))

/* GPIOC AHB ADCEN BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL_ADCEN0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL) + (GPIO_GPIOCDCCTL_R_ADCEN0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL_ADCEN1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL) + (GPIO_GPIOCDCCTL_R_ADCEN1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL_ADCEN2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL) + (GPIO_GPIOCDCCTL_R_ADCEN2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL_ADCEN3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL) + (GPIO_GPIOCDCCTL_R_ADCEN3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL_ADCEN4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL) + (GPIO_GPIOCDCCTL_R_ADCEN4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL_ADCEN5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL) + (GPIO_GPIOCDCCTL_R_ADCEN5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL_ADCEN6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL) + (GPIO_GPIOCDCCTL_R_ADCEN6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIOCDCCTL_ADCEN7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCDCCTL_OFFSET) * 32UL) + (GPIO_GPIOCDCCTL_R_ADCEN7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 24 GPIODMACTL *********************************************
 ******************************************************************************************/
/* GPIOC AHB DMAEN*/
#define GPIOC_AHB_BITBANDING_GPIODMACTL    ((BITBANDING_GPIODMACTL_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL)))

/* GPIOC AHB DMAEN BITBANDING*/
#define GPIOC_AHB_BITBANDING_GPIODMACTL_DMAEN0    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL) + (GPIO_GPIODMACTL_R_DMAEN0_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODMACTL_DMAEN1    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL) + (GPIO_GPIODMACTL_R_DMAEN1_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODMACTL_DMAEN2    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL) + (GPIO_GPIODMACTL_R_DMAEN2_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODMACTL_DMAEN3    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL) + (GPIO_GPIODMACTL_R_DMAEN3_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODMACTL_DMAEN4    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL) + (GPIO_GPIODMACTL_R_DMAEN4_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODMACTL_DMAEN5    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL) + (GPIO_GPIODMACTL_R_DMAEN5_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODMACTL_DMAEN6    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL) + (GPIO_GPIODMACTL_R_DMAEN6_BIT * 4UL))))
#define GPIOC_AHB_BITBANDING_GPIODMACTL_DMAEN7    (*((volatile uint32_t *) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIODMACTL_OFFSET) * 32UL) + (GPIO_GPIODMACTL_R_DMAEN7_BIT * 4UL))))

/******************************************************************************************
 *********************************** * 25 GPIOPeriphID4 *********************************************
 ******************************************************************************************/
/* GPIOC AHB PID4*/
#define GPIOC_AHB_BITBANDING_GPIOPeriphID4    ((BITBANDING_GPIOPeriphID4_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPeriphID4_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 26 GPIOPeriphID5 *********************************************
 ******************************************************************************************/
/* GPIOC AHB PID5*/
#define GPIOC_AHB_BITBANDING_GPIOPeriphID5    ((BITBANDING_GPIOPeriphID5_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPeriphID5_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 27 GPIOPeriphID6 *********************************************
 ******************************************************************************************/
/* GPIOC AHB PID6*/
#define GPIOC_AHB_BITBANDING_GPIOPeriphID6    ((BITBANDING_GPIOPeriphID6_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPeriphID6_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 28 GPIOPeriphID7 *********************************************
 ******************************************************************************************/
/* GPIOC AHB PID7*/
#define GPIOC_AHB_BITBANDING_GPIOPeriphID7    ((BITBANDING_GPIOPeriphID7_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPeriphID7_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 29 GPIOPeriphID0 *********************************************
 ******************************************************************************************/
/* GPIOC AHB PID0*/
#define GPIOC_AHB_BITBANDING_GPIOPeriphID0    ((BITBANDING_GPIOPeriphID0_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPeriphID0_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 30 GPIOPeriphID1 *********************************************
 ******************************************************************************************/
/* GPIOC AHB PID1*/
#define GPIOC_AHB_BITBANDING_GPIOPeriphID1    ((BITBANDING_GPIOPeriphID1_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPeriphID1_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 31 GPIOPeriphID2 *********************************************
 ******************************************************************************************/
/* GPIOC AHB PID2*/
#define GPIOC_AHB_BITBANDING_GPIOPeriphID2    ((BITBANDING_GPIOPeriphID2_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPeriphID2_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 32 GPIOPeriphID3 *********************************************
 ******************************************************************************************/
/* GPIOC AHB PID3*/
#define GPIOC_AHB_BITBANDING_GPIOPeriphID3    ((BITBANDING_GPIOPeriphID3_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOPeriphID3_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 33 GPIOCellID0 *********************************************
 ******************************************************************************************/
/* GPIOC AHB CID0*/
#define GPIOC_AHB_BITBANDING_GPIOCellID0    ((BITBANDING_GPIOCellID0_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCellID0_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 34 GPIOCellID1 *********************************************
 ******************************************************************************************/
/* GPIOC AHB CID1*/
#define GPIOC_AHB_BITBANDING_GPIOCellID1    ((BITBANDING_GPIOCellID1_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCellID1_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 35 GPIOCellID2 *********************************************
 ******************************************************************************************/
/* GPIOC AHB CID2*/
#define GPIOC_AHB_BITBANDING_GPIOCellID2    ((BITBANDING_GPIOCellID2_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCellID2_OFFSET) * 32UL)))

/******************************************************************************************
 *********************************** * 36 GPIOCellID3 *********************************************
 ******************************************************************************************/
/* GPIOC AHB CID3*/
#define GPIOC_AHB_BITBANDING_GPIOCellID3    ((BITBANDING_GPIOCellID3_TypeDef*) (GPIO_BITBANDING_BASE + ((GPIOC_AHB_OFFSET + GPIO_GPIOCellID3_OFFSET) * 32UL)))

#endif /* XDRIVER_MCU_DRIVER_HEADER_GPIO_GPIO_PERIPHERAL_GPIO_REGISTER_GPIO_REGISTERPERIPHERAL_BITBANDING_GPIO_REGISTERPERIPHERAL_AHB_BITBANDING_GPIO_REGISTERPERIPHERAL_AHB_BITBANDING_MODULEC_H_ */
