/**
 *
 * @file PWM_Enum.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim May 26, 2021 @endverbatim
 *
 * @author
 * @verbatim indevicemex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * May 26, 2021        indevicemex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_PWM_PERIPHERAL_XHEADER_PWM_ENUM_H_
#define XDRIVER_MCU_PWM_PERIPHERAL_XHEADER_PWM_ENUM_H_

#include <xDriver_MCU/Common/xHeader/MCU_Variables.h>

typedef enum
{
    PWM_enSTATUS_OK = 0UL,
    PWM_enSTATUS_ERROR = 1UL,
    PWM_enSTATUS_UNDEF = 0xFFFFFFFFUL,
}PWM_nSTATUS;


typedef enum
{
    PWM_enSTATE_FALSE = 0UL,
    PWM_enSTATE_TRUE = 1UL,
    PWM_enSTATE_UNDEF = 0xFFFFFFFFUL,
}PWM_nSTATE;

typedef enum
{
    PWM_enNOREADY = 0UL,
    PWM_enREADY = 1UL,
}PWM_nREADY;

typedef enum
{
    PWM_enMODULE_0 = 0UL,
    PWM_enMODULE_1 = 1UL,
    PWM_enMODULE_MAX = 2UL,
}PWM_nMODULE;

typedef enum
{
    PWM_enPRI0 = 0UL,
    PWM_enPRI1 = 1UL,
    PWM_enPRI2 = 2UL,
    PWM_enPRI3 = 3UL,
    PWM_enPRI4 = 4UL,
    PWM_enPRI5 = 5UL,
    PWM_enPRI6 = 6UL,
    PWM_enPRI7 = 7UL,
    PWM_enPRIMAX = 7UL,
    PWM_enDEFAULT = 0xFFFFFFFFUL,
}PWM_nPRIORITY;

typedef enum
{
    PWM_enGEN_0 = 0UL,
    PWM_enGEN_1 = 1UL,
    PWM_enGEN_2 = 2UL,
    PWM_enGEN_3 = 3UL,
    PWM_enGEN_MAX = 4UL,
    PWM_enGEN_UNDEF = 0xFFFFFFFFUL,
}PWM_nGENERATOR;

typedef enum
{
    PWM_enFAULT_0 = 0UL,
    PWM_enFAULT_1 = 1UL,
    PWM_enFAULT_2 = 2UL,
    PWM_enFAULT_3 = 3UL,
    PWM_enFAULT_MAX = 4UL,
    PWM_enFAULT_UNDEF = 0xFFFFFFFFUL,
}PWM_nFAULT;

typedef enum
{
    PWM_enGENMASK_NONE = 0x0UL,
    PWM_enGENMASK_0 = 0x1UL,
    PWM_enGENMASK_1 = 0x2UL,
    PWM_enGENMASK_2 = 0x4UL,
    PWM_enGENMASK_3 = 0x8UL,
    PWM_enGENMASK_MAX = 0xFUL,
    PWM_enGENMASK_UNDEF = 0xFFFFFFFFUL,
}PWM_nGENMASK;

typedef enum
{
    PWM_enFAULTMASK_NONE = 0x0UL,
    PWM_enFAULTMASK_0 = 0x1UL,
    PWM_enFAULTMASK_1 = 0x2UL,
    PWM_enFAULTMASK_2 = 0x4UL,
    PWM_enFAULTMASK_3 = 0x8UL,
    PWM_enFAULTMASK_ALL = 0xFUL,
    PWM_enFAULTMASK_UNDEF = 0xFFFFFFFFUL,
}PWM_nFAULTMASK;

/**
 * PWM Gen interrupts
 */
typedef enum
{
    PWM_enGEN_INTERRUPT_SW = 0UL,
    PWM_enGEN_INTERRUPT_ZERO = 1UL,
    PWM_enGEN_INTERRUPT_LOAD = 2UL,
    PWM_enGEN_INTERRUPT_CMPA_UP = 3UL,
    PWM_enGEN_INTERRUPT_CMPA_DOWN = 4UL,
    PWM_enGEN_INTERRUPT_CMPB_UP = 5UL,
    PWM_enGEN_INTERRUPT_CMPB_DOWN = 6UL,
    PWM_enGEN_INTERRUPT_MAX = 7UL,
}PWM_nGEN_INTERRUPT;

typedef enum
{
    PWM_enGEN_INT_SOURCE_NONE = 0x0UL,
    PWM_enGEN_INT_SOURCE_ZERO = 0x1UL,
    PWM_enGEN_INT_SOURCE_LOAD = 0x2UL,
    PWM_enGEN_INT_SOURCE_CMPA_UP = 0x4UL,
    PWM_enGEN_INT_SOURCE_CMPA_DOWN = 0x8UL,
    PWM_enGEN_INT_SOURCE_CMPB_UP = 0x10UL,
    PWM_enGEN_INT_SOURCE_CMPB_DOWN = 0x20UL,
    PWM_enGEN_INT_SOURCE_ALL = 0x3FUL,
}PWM_nGEN_INT_SOURCE;


/**
 * PWM Gen interrupts
 */
typedef enum
{
    PWM_enFAULT_INTERRUPT_SW = 0UL,
    PWM_enFAULT_INTERRUPT_FAULT = 1UL,
    PWM_enFAULT_INTERRUPT_MAX = 2UL,
}PWM_nFAULT_INTERRUPT;

typedef enum
{
    PWM_enFAULT_INT_SOURCE_NONE = 0x0UL,
    PWM_enFAULT_INT_SOURCE_FAULT = 0x1UL,
    PWM_enFAULT_INT_SOURCE_ALL = 0x1UL,
}PWM_nFAULT_INT_SOURCE;

typedef enum
{
    PWM_enINT_STATUS_NOOCCUR = 0UL,
    PWM_enINT_STATUS_OCCUR = 1UL,
    PWM_enINT_STATUS_UNDEF = 0xFFFFFFFFUL,
}PWM_nINT_STATUS;

typedef enum
{
    PWM_enDEADBAND_ENABLE_DIS = 0x0UL,
    PWM_enDEADBAND_ENABLE_ENA = 0x1UL,
    PWM_enDEADBAND_ENABLE_UNDEF = 0xFFFFFFFFUL,
}PWM_nDEADBAND_ENABLE;

typedef enum
{
    PWM_enDEADBAND_UPDATE_IMMEDIATE = 0x0UL,
    PWM_enDEADBAND_UPDATE_LOCAL = 0x2UL,
    PWM_enDEADBAND_UPDATE_GLOBAL = 0x3UL,
    PWM_enDEADBAND_UPDATE_UNDEF = 0xFFFFFFFFUL,
}PWM_nDEADBAND_UPDATE;

typedef enum
{
    PWM_enFAULT_INPUT_NONE = 0x0UL,
    PWM_enFAULT_INPUT_0 = 0x1UL,
    PWM_enFAULT_INPUT_1 = 0x2UL,
    PWM_enFAULT_INPUT_2 = 0x4UL,
    PWM_enFAULT_INPUT_3 = 0x8UL,
    PWM_enFAULT_INPUT_UNDEF = 0xFFFFFFFFUL,
}PWM_nFAULT_INPUT;

typedef enum
{
    PWM_enFAULT_INPUT_SENSE_HIGH = 0x0UL,
    PWM_enFAULT_INPUT_SENSE_LOW = 0x1UL,
    PWM_enFAULT_INPUT_SENSE_UNDEF = 0xFFFFFFFFUL,
}PWM_nFAULT_INPUT_SENSE;

typedef enum
{
    PWM_enFAULT_MINPERIOD_ENABLE_DIS = 0x0UL,
    PWM_enFAULT_MINPERIOD_ENABLE_ENA = 0x1UL,
    PWM_enFAULT_MINPERIOD_ENABLE_UNDEF = 0xFFFFFFFFUL,
}PWM_nFAULT_MINPERIOD_ENABLE;

typedef enum
{
    PWM_enFAULT_LATCH_ENABLE_DIS = 0x0UL,
    PWM_enFAULT_LATCH_ENABLE_ENA = 0x1UL,
    PWM_enFAULT_LATCH_ENABLE_UNDEF = 0xFFFFFFFFUL,
}PWM_nFAULT_LATCH_ENABLE;

typedef enum
{
    PWM_enFAULT_DCOMP_NONE = 0x0UL,
    PWM_enFAULT_DCOMP_0 = 0x1UL,
    PWM_enFAULT_DCOMP_1 = 0x2UL,
    PWM_enFAULT_DCOMP_2 = 0x4UL,
    PWM_enFAULT_DCOMP_3 = 0x8UL,
    PWM_enFAULT_DCOMP_4 = 0x10UL,
    PWM_enFAULT_DCOMP_5 = 0x20UL,
    PWM_enFAULT_DCOMP_6 = 0x40UL,
    PWM_enFAULT_DCOMP_7 = 0x80UL,
    PWM_enFAULT_DCOMP_UNDEF = 0xFFFFFFFFUL,
}PWM_nFAULT_DCOMP;

typedef enum
{
    PWM_enGENERATOR_ENABLE_DIS = 0x0UL,
    PWM_enGENERATOR_ENABLE_ENA = 0x1UL,
    PWM_enGENERATOR_ENABLE_UNDEF = 0xFFFFFFFFUL,
}PWM_nGENERATOR_ENABLE;

typedef enum
{
    PWM_enGENERATOR_UPDATE_IMMEDIATE = 0x0UL,
    PWM_enGENERATOR_UPDATE_LOCAL = 0x2UL,
    PWM_enGENERATOR_UPDATE_GLOBAL = 0x3UL,
    PWM_enGENERATOR_UPDATE_UNDEF = 0xFFFFFFFFUL,
}PWM_nGENERATOR_UPDATE;


typedef enum
{
    PWM_enOUTPUT_NUMBER_NONE = 0x0UL,
    PWM_enOUTPUT_NUMBER_GEN0A = 0x1UL,
    PWM_enOUTPUT_NUMBER_GEN0B = 0x2UL,
    PWM_enOUTPUT_NUMBER_GEN1A = 0x4UL,
    PWM_enOUTPUT_NUMBER_GEN1B = 0x8UL,
    PWM_enOUTPUT_NUMBER_GEN2A = 0x10UL,
    PWM_enOUTPUT_NUMBER_GEN2B = 0x20UL,
    PWM_enOUTPUT_NUMBER_GEN3A = 0x40UL,
    PWM_enOUTPUT_NUMBER_GEN3B = 0x80UL,
    PWM_enOUTPUT_NUMBER_ALL = 0xFFUL,
    PWM_enOUTPUT_NUMBER_UNDEF = 0xFFFFFFFFUL,
}PWM_nOUTPUT_NUMBER;

typedef enum
{
    PWM_enOUTPUT_NONE = 0x0UL,
    PWM_enOUTPUT_A = 0x1UL,
    PWM_enOUTPUT_B = 0x2UL,
    PWM_enOUTPUT_BOTH = 0x3UL,
    PWM_enOUTPUT_UNDEF = 0xFFFFFFFFUL,
}PWM_nOUTPUT;

typedef enum
{
    PWM_enOUTPUT_UPDATE_IMMEDIATE = 0x0UL,
    PWM_enOUTPUT_UPDATE_LOCAL = 0x2UL,
    PWM_enOUTPUT_UPDATE_GLOBAL = 0x3UL,
    PWM_enOUTPUT_UPDATE_UNDEF = 0xFFFFFFFFUL,
}PWM_nOUTPUT_UPDATE;

typedef enum
{
    PWM_enOUTPUT_ENABLE_DIS = 0x0UL,
    PWM_enOUTPUT_ENABLE_ENA = 0x1UL,
    PWM_enOUTPUT_ENABLE_UNDEF = 0xFFFFFFFFUL,
}PWM_nOUTPUT_ENABLE;

typedef enum
{
    PWM_enOUTPUT_FAULT_LOW = 0x0UL,
    PWM_enOUTPUT_FAULT_HIGH = 0x1UL,
    PWM_enOUTPUT_FAULT_UNDEF = 0xFFFFFFFFUL,
}PWM_nOUTPUT_FAULT;

typedef enum
{
    PWM_enACTION_NOTHING = 0x0UL,
    PWM_enACTION_INVERT = 0x1UL,
    PWM_enACTION_LOW = 0x2UL,
    PWM_enACTION_HIGH = 0x3UL,
    PWM_enACTION_UNDEF = 0xFFFFFFFFUL,
}PWM_nACTION;

typedef enum
{
    PWM_enEVENT_ZERO = 0x0UL,
    PWM_enEVENT_LOAD = 0x1UL,
    PWM_enEVENT_COMPA_UP = 0x2UL,
    PWM_enEVENT_COMPA_DOWN = 0x3UL,
    PWM_enEVENT_COMPB_UP = 0x4UL,
    PWM_enEVENT_COMPB_DOWN = 0x5UL,
    PWM_enEVENT_UNDEF = 0xFFFFFFFFUL,
}PWM_nEVENT;

typedef enum
{
    PWM_enDIRECTION_DOWN = 0x0UL,
    PWM_enDIRECTION_UP_DOWN = 0x1UL,
    PWM_enDIRECTION_UNDEF = 0xFFFFFFFFUL,
}PWM_nDIRECTION;


typedef enum
{
    PWM_enSTALL_FREEZE = 0UL,
    PWM_enSTALL_CONTINUE = 1UL,
    PWM_enSTALL_UNDEF = 0xFFFFFFFFUL,
}PWM_nSTALL;

typedef enum
{
    PWM_enCLOCK_SYSCLK = 0x0UL,
    PWM_enCLOCK_DIVIDER = 0x1UL,
    PWM_enCLOCK_UNDEF = 0xFFFFFFFFUL,
}PWM_nCLOCK;

typedef enum
{
    PWM_enCLOCK_DIV_2 = 0x0UL,
    PWM_enCLOCK_DIV_4 = 0x1UL,
    PWM_enCLOCK_DIV_8 = 0x2UL,
    PWM_enCLOCK_DIV_16 = 0x3UL,
    PWM_enCLOCK_DIV_32 = 0x4UL,
    PWM_enCLOCK_DIV_64 = 0x5UL,
    PWM_enCLOCK_DIV_MAX = 0x5UL,
    PWM_enCLOCK_DIV_UNDEF = 0xFFFFFFFFUL,
}PWM_nCLOCK_DIV;

typedef enum
{
    PWM_enCLOCK_DIV_NUM_2 = 0x2UL,
    PWM_enCLOCK_DIV_NUM_4 = 0x4UL,
    PWM_enCLOCK_DIV_NUM_8 = 0x8UL,
    PWM_enCLOCK_DIV_NUM_16 = 16UL,
    PWM_enCLOCK_DIV_NUM_32 = 32UL,
    PWM_enCLOCK_DIV_NUM_64 = 64UL,
    PWM_enCLOCK_DIV_NUM_MASK = 0x7FUL,
    PWM_enCLOCK_DIV_NUM_UNDEF = 0xFFFFFFFFUL,
}PWM_nCLOCK_DIV_NUM;

#endif /* XDRIVER_MCU_PWM_PERIPHERAL_XHEADER_PWM_ENUM_H_ */
